### ISSUE TITLE
MapControl: Cannot add pins to the map in WPF

### ISSUE THREAD

**Issue by JuanPapas** [windows-toolkit/Microsoft.Toolkit.Win32#112]
## I'm submitting a...
Bug report (I searched for similar issues and did not find one)
Please do see issue #62 which could be related.

## Current behavior
Cannot add pins to the map when using the WPF wrapper.  This repros whether one tries to add elements to the MapControl.MapElements collection directly or to a MapElementsLayer.MapElements collection which is then added to the MapControl.
Looks like:
* MapElements collection is null in the WPF wrapper for Xaml MapControl
* MapElementsLayer's MapElements collection appears to have a similar problem too.

## Expected behavior
One can add pins to the map using either approach.

## Minimal reproduction of the problem with instructions
**Approach 1**
``` 
MapIcon mapIcon1 = new MapIcon
{
    Location = new Geopoint(new BasicGeoposition() { Latitude = 47.604, Longitude = -122.329 }),
    Image = RandomAccessStreamReference.CreateFromUri(new Uri("ms-appx:///Assets/MapPin.png"))
};
 
myMap.MapElements.Add(mapIcon1);
```
 
**Approach 2**
``` 
List<MapElement> elements = new List<MapElement>();
elements.Add(mapIcon1);
 
MapElementsLayer layer = new MapElementsLayer
{
    ZIndex = 1,
    MapElements = elements
};
 
mapControl1.Layers.Add(layer)
```

## Environment
```
Nuget Package(s): 

Package Version(s): 

Windows 10 Build Number:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [ x ] Insider Build (1903: 18362)

App min and target version:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [ x ] Insider Build (1903: 18362)

Device form factor:
- [ x ] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

Visual Studio 
- [ x ] 2017 (version: )
- [ ] 2017 Preview (version: )

```

**Comment by azchohfi** [comment]
This should be fixed in the latest MyGet. Please, test and reopen the issue if it's still a problem.
