### ISSUE TITLE
Horizontal touchpad and mouse scrolling does not work with XAML host hosted content

### ISSUE THREAD

**Issue by aquinn39** [windows-toolkit/Microsoft.Toolkit.Win32#117]
## I'm submitting a...

Bug report (I searched for similar issues and did not find one)
 

## Current behavior

Attempting to scroll a textbox or scrollviewer in an XAML host horizontally using the horizontal scrolling gesture on touchpad or mouse wheel tilt on a mouse does not do anything in Windows 10 version 1903. From memory, it used to work in Windows 10 version 1809.

## Expected behavior

Content should scroll when scrolling horizontal with a mouse or a touchpad

## Minimal reproduction of the problem with instructions

Create a WPF app and add an XAML host that contains a scrollviewer or textbox and try to scroll the textbox or scrollviewer horizontally with a mouse or touchpad. 

## Environment

```
Nuget Package(s): 
Microsoft.Toolkit.Forms.UI.XamlHost - 6.0.0-preview5
Microsoft.Toolkit.Wpf.UI.XamlHost - 6.0.0-preview5
Microsoft.Windows.SDK.Contracts - 10.0.18362.2002-preview


Windows 10 Build Number:
[x] Insider Build (build number: 18362.86)

App min and target version:
 [x] Insider Build (18358.0)

Device form factor:
[x] Desktop


Visual Studio 
[x] 2019 (version: 16.0.3)

```

**Comment by azchohfi** [comment]
@marb2000 is this a known issue?

**Comment by michael-hawker** [comment]
Talked to @marb2000 and @ocalvo, it was a known OS version issue.  It should be fixed through OS servicing in the near future.
