### ISSUE TITLE
System.Runtime.InteropServices.WindowsRuntime Invalid Reference

### ISSUE THREAD

**Issue by duke7553** [windows-toolkit/Microsoft.Toolkit.Win32#122]
## I'm submitting a...

Bug report (I searched for similar issues and did not find one)
 

## Current behavior
Attempting to reference **System.Runtime.InteropServices.WindowsRuntime** for XAML Islands in a VS 2019 .NET Core WPF project results in an error as pictured below.
![Annotation 2019-05-15 192932](https://user-images.githubusercontent.com/20365014/57816043-d9162000-7747-11e9-8424-12ae962a9d13.png)

## Expected behavior
The reference should work properly.

## Environment

```
Nuget Package(s): N/A

Package Version(s): N/A

Windows 10 Build Number:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [x] May 2019 Update (18362.86)
- [ ] Insider Build (build number: )

App min and target version: (N/A)
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [ ] Insider Build (xxxxx)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

Visual Studio 
- [ ] 2017 (version: )
- [ ] 2017 Preview (version: )
- [x] 2019 (version: 16.0.3)
```

**Comment by azchohfi** [comment]
Try using the preview version of the Windows community toolkit nuget package and you shouldn't need to manually reference this other nuget at all.

**Comment by duke7553** [comment]
@azchohfi Other nuget? These were system dlls.

**Comment by azchohfi** [comment]
Why are you trying to reference them? If you are trying this for .Net core, you need to use the 6.0.0-previewX version (5 being the latest). Preview 4 added support for a different way to reference the glue assemblies. You don't need to add a reference to System.Runtime.InteropServices.WindowsRuntime.

**Comment by duke7553** [comment]
@azchohfi I was following the instructions from here: https://docs.microsoft.com/en-us/windows/uwp/xaml-platform/xaml-host-controls#requirements

**Comment by azchohfi** [comment]
Yeah, that works fine for .Net Framework, but for dot net core:
https://docs.microsoft.com/en-us/windows/uwp/xaml-platform/xaml-host-controls#feature-roadmap

**Comment by duke7553** [comment]
Thank you. I'll close this now.
