### ISSUE TITLE
Missing dep when downloading Microsoft.Toolkit.Forms.UI.XamlHost v6.0.0-preview6

### ISSUE THREAD

**Issue by JosephMart** [windows-toolkit/Microsoft.Toolkit.Win32#130]
## I'm submitting a...

Bug report (I searched for similar issues and did not find one)

 

## Current behavior

Package not found (`Microsoft.Toolkit.Win32.UI.XamlApplication`) when installing `Microsoft.Toolkit.Forms.UI.XamlHost v6.0.0-preview6` through NuGet in Visual Studio. `Microsoft.Toolkit.Forms.UI.XamlHost v6.0.0-preview5` worked just fine.

Error:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1101	Unable to find package Microsoft.Toolkit.Win32.UI.XamlApplication. No packages exist with this id in source(s): https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore-tooling/index.json, https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore/index.json, https://dotnetfeed.blob.core.windows.net/aspnet-entityframeworkcore/index.json, https://dotnetfeed.blob.core.windows.net/aspnet-extensions/index.json, https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json, https://dotnetfeed.blob.core.windows.net/dotnet-windowsdesktop/index.json, Microsoft Visual Studio Offline Packages, nuget.org	WinFormProj	C:\Users\josmarti\dev\WinFormProj\WinFormProj.csproj	1	
```

## Expected behavior

`Microsoft.Toolkit.Forms.UI.XamlHost v6.0.0-preview6` to download and install.

## Minimal reproduction of the problem with instructions

Try to download/install `Microsoft.Toolkit.Forms.UI.XamlHost v6.0.0-preview6`  through NuGet

## Environment

```
Nuget Package(s): 

Package Version(s): `Microsoft.Toolkit.Forms.UI.XamlHost v6.0.0-preview6` 

Windows 10 Build Number:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [x] Insider Build (build number: 18362)

App min and target version:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [ ] Insider Build (19H1 -- 1903)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

Visual Studio 
- [ ] 2017 (version: )
- [ ] 2017 Preview (version: )
- [x] 2019 Preview (version: 16.2.0 Preview 2.0)

```

**Comment by azchohfi** [comment]
That as a known issue that we are working internally to fix.

**Comment by Lakritzator** [comment]
What worked for me, was adding the following to the packagesources in my NuGet.Config

`<add key="uwpcommunitytoolkit" value="https://dotnet.myget.org/F/uwpcommunitytoolkit/api/v3/index.json" />`

**Comment by azchohfi** [comment]
That solved the problem from now, but I wouldn't recommend doing this as new MyGet packages might be added as dependencies, and break stuff.

**Comment by azchohfi** [comment]
Package was published, and the issue should be no more.
