### ISSUE TITLE
Xaml Islands - 'Windows.UI.Xaml.Markup.XamlParseException' 

### ISSUE THREAD

**Issue by grubioe** [windows-toolkit/Microsoft.Toolkit.Win32#148]
Copied from [WPF Issue #1328](https://github.com/dotnet/wpf/issues/1328)
Authored by @ken30096

# Xaml Islands - 'Windows.UI.Xaml.Markup.XamlParseException'
Using the following Microsoft documentation - "WindowsXamlHost control for Windows Forms and WPF", I am attempting to complete the following exercise: [Add a custom UWP control](https://docs.microsoft.com/en-us/windows/communitytoolkit/controls/wpf-winforms/windowsxamlhost#add-a-custom-uwp-control). After carefully following the documentation I get the following error "Xaml parsing failed". See below for further details.

## Error
<code>
Exception thrown at 0x00007FF9C8BAA839 (KernelBase.dll) in TestWPFApp.exe: WinRT originate error - 0x80004005 : 'Cannot locate resource from 'ms-appx:///UWPClassLibrary/MyPage.xaml'.'.
onecore\com\combase\winrt\error\restrictederror.cpp(1014)\combase.dll!00007FF9C97EB690: (caller: 00007FF9C97E60BC) ReturnHr(1) tid(2f80) 8007007E The specified module could not be found.
Exception thrown: 'Windows.UI.Xaml.Markup.XamlParseException' in TestWPFApp.exe
The thread 0x54b4 has exited with code 0 (0x0).
</code>

## Research
I made certain that I did not accidentally step on the xaml code that I was instructed to insert into MyPage.xaml by removing it and I got the same error. It seems to me WPF is trying to locate a UWP Class Library as a locally defined resource but this is Xaml Island not WPF. If that is indeed the case, how do I do this? Are instructions missing from documentation? This is not just a futile exercise, I need to know how to create a UWP user control for my WPF project. I am using the exercise as a first step. You can repeat the error by following the documentation. I created a video that completes the full exercise up to the point of the error and my attempt to resolve it. Since I know you are pressed for time, as always, the error occurs at minute: 22:14. Click on this link to review the video: [Xaml Islands - Add a custom UWP control](https://www.youtube.com/watch?v=oMH7aPd9xvM)

>Does the bug reproduce also in WPF for .NET Framework 4.8?: Yes! <br>

## Sofware used to build the application:
<ul>
  <li>Microsoft Visual Studio Community 2019 Preview (version 16.2.0 Preview 4.0).</li>
  <li>Windows 10 Pro 1903 OS Build 18362.10005</li>
  <li>WPF .Net Framework 4.7.2 using C#</li>
  <li>Windows Application Packaging
    <ul id="list2">
        <li>Target version: Windows 10. version 1903 (10.0; Build 18362)</li>
        <li>Min version:    Windows 10. version 1903 (10.0; Build 18362)</li>
    </ul>
  </li>  
  <li>NuGet Packages
    <ul id="list2">
        <li>Microsoft.Windows.SDK.Contracts (v10.0.18362.2002-preview)</li>
        <li>Microsoft.Toolkit.Wpf.UI.XamlHost (v6.0.0-preview6.4)</li>
    </ul>
  </li>  
</ul>
<br>

## Clean object and bin folder - failed:<br> 

I used the following StackOverflow article as a guide on [How to clean Visual Studio bin and obj folders](https://stackoverflow.com/questions/1088593/how-to-clean-visual-studio-bin-and-obj-folders)  I unloaded UWPClassLibrary.csproj and added the following code just before the last statement: 

```
  <Target Name="SpicNSpan" AfterTargets="Clean">
    <RemoveDir Directories="$(TargetDir)" />
    <!-- bin -->
    <RemoveDir Directories="$(ProjectDir)$(BaseIntermediateOutputPath)" />
    <!-- obj -->
  </Target>
```
<p>
and reloaded the project. I right-clicked on the UWPClassLibrary and selected "Build". I am assuming by "restore" you are referring to NuGet Packages. I had previously set the following option in VS2019CE: In Tools -> Options -> NuGet Package Manager -> General, select the "Allow NuGet to download missing packages" option which allows NuGet to restore and then "Automatically check for missing packages during build in Visual Studio" which enables on build restore.  I then rebuilt the solution and received the same error. 
</p>

Since I was uncertain of what effect  cleaning the object and bin folder was supposed to have, I downloaded  [Clean Bin and Obj](https://marketplace.visualstudio.com/items?itemName=dobrynin.cleanbinandobj) from the Marketplace and ran it. It produced the following:

<p>
18:58:41.4890: Starting... Projects to clean: 3<br>
18:58:41.5049: Cleaning BuildWAP\BuildWAP.wapproj<br>
18:58:41.5368: Cleaning TestWPFApp\TestWPFApp.csproj<br>
18:58:41.5539: Cleaning UWPClassLibrary\UWPClassLibrary.csproj<br>
18:58:41.5697: Finished. Process took 00:00.0680
</p>
<p>
I got the same results. In addition I totally rebuilt the project from scratch, implemented the suggested proposal again and got the same results!
</p>

**Comment by azchohfi** [comment]
.NET Framework WPF projects cannot instantiate Managed UWP controls. You can only use managed UWP custom controls within a .NET **Core** WPF or WinForms app.

**Comment by ken30096** [comment]
I tested this issue on 3 platforms:<br>.Net Framework 4.7.2<br>.Net Framework 8<br>.Net Core 3.0<br> Each time I got the same error! I created a [video](https://www.youtube.com/watch?v=0fMxGrkHuHg)  of the exercise using .Net Core 3.0 (minute 01:04) and the subsequent  error (minute 16:57). Before I opened this issue, I tried very hard to  make certain it was an issue.

**Comment by vladabuba** [comment]
> .NET Framework WPF projects cannot instantiate Managed UWP controls. You can only use managed UWP custom controls within a .NET **Core** WPF or WinForms app.

Hi, I'm a bit confused that only WPF .Net core projects can work with UWP managed controls. I see your example here, and it works with .NET Framework 4.7.2? ... 

https://github.com/microsoft/XamlIslandBlogPostSample

Also I had created WPF 4.7.2 project and I can use UWP standard controls and user controls from UWP library and they do work, so now I'm confused about your statement?...

**Comment by azchohfi** [comment]
Xaml island works in the same process as your App. You cannot load both the DotNet Core managed runtime, and the DotNet Framework managed runtime, and use them interchangeably. When you create a C# UWP Project and create your custom controls, you are pretty much using the DotNet Core runtime, so if you want to do that, if will only work with DotNet Core. If the custom control is C++ (non managed) or the host is a C++ (non managed) Win32 process, that does not load the dotnet framework mamaged, it should work.

**Comment by vladabuba** [comment]
> Xaml island works in the same process as your App. You cannot load both the DotNet Core managed runtime, and the DotNet Framework managed runtime, and use them interchangeably. When you create a C# UWP Project and create your custom controls, you are pretty much using the DotNet Core runtime, so if you want to do that, if will only work with DotNet Core. If the custom control is C++ (non managed) or the host is a C++ (non managed) Win32 process, that does not load the dotnet framework mamaged, it should work.

Hi, thanks for reply. I think I understand technological foundation for this - you can not mix WPF and UWP. But then, please could you explain me how then does this example and WPF application with UWP control inside it works, from application project you had posted on github? I need this so I can explain this to my customer that demands that I use UWP tree control inside WPF application. This is very serious, my job and work depends on this!

**Comment by vladabuba** [comment]
Here is your project (it shows Net Framework 4.7.2 in client app):
![image](https://user-images.githubusercontent.com/9928044/62478621-cee64980-b7ab-11e9-9e7a-9317a7b48055.png)

And here is UWP library from same solution:
![image](https://user-images.githubusercontent.com/9928044/62478651-e02f5600-b7ab-11e9-97eb-10a92f1a469a.png)

So I'm puzzled now how this works based on your comment?

**Comment by azchohfi** [comment]
This is a recompilation, not type loading, and I'm also sure this is not supported anymore. @marb2000 do you happen to know? I'm rebuilding the generated files (inside the obj folder) from the UWP project (*.g.cs, *.g.i.cs, XamlTypeInfo.g.cs, etc) using .Net Framework, so they are not .Net Core anymore. You cannot load a type that was built UWP (UWP Class library, etc).

**Comment by vladabuba** [comment]
Hi, thanks for reply. Please could you point me to some official report regarding that using UWP custom controls in WPF .NET Framework (like 4.7.x) is not supported anymore. I need this to show to my client so he can understand why we can not use UWP custom controls in our huge WPF .NET Framework application.

**Comment by marb2000** [comment]
Hi, 
In my blog post about [XAML Islands v1](https://blogs.windows.com/windowsdeveloper/2019/06/13/xaml-islands-v1-updates-and-roadmap/), I made public that Managed 3rd party controls are no supported when the host is .NET Framework. You can find in the section: "What versions of .NET Core and .NET Framework can I target with XAML Islands?" You will see a red-cross. The cross-compilation workaround works in some scenarios, but there is no guarantee it works always and it is not supported.

**Comment by vladabuba** [comment]
Hi, Thanks for reply. I understand that we can try but there is no guarantee that it will work. I will going to relay this to our customer.

> 
> 
> Hi,
> In my blog post about [XAML Islands v1](https://blogs.windows.com/windowsdeveloper/2019/06/13/xaml-islands-v1-updates-and-roadmap/), I made public that Managed 3rd party controls are no supported when the host is .NET Framework. You can find it in the section: "What versions of .NET Core and .NET Framework can I target with XAML Islands?" You will see a red-cross. The cross-compilation workaround works in some scenarios, but there is no guarantee it works always and it is not supported.

**Comment by kallidean** [comment]
> I tested this issue on 3 platforms:
> .Net Framework 4.7.2
> .Net Framework 8
> .Net Core 3.0
> Each time I got the same error! I created a [video](https://www.youtube.com/watch?v=-4qnzzfydU0) of the exercise using .Net Core 3.0 (minute 01:04) and the subsequent error (minute 15:40). Before I opened this issue, I tried very hard to make certain it was an issue.

I have run into this same problem with the latest 9.1 preview package.  When I run after a rebuild, it fails.  When I restart the execution, the control renders.  Restart again, fails.  Restart again, renders.  It basically works 50% of the time.

If I roll back to 7.1 things work fine.

I tried UWP application with <XamlApplication> types, and a UWP Class Library.  Both with views and user controls.  The behavior is the same.

If anyone has any suggestions, I would really appreciate some guidance here.  It's very frustrating to be stuck on an old preview version of the toolkit due to these issues with XamlHost.

**Comment by marb2000** [comment]
What version of Visual Studio 2019 are you using? () We are working with the VS team on making this smoother.

**Comment by derMaaster** [comment]
> > I tested this issue on 3 platforms:
> > .Net Framework 4.7.2
> > .Net Framework 8
> > .Net Core 3.0
> > Each time I got the same error! I created a [video](https://www.youtube.com/watch?v=-4qnzzfydU0) of the exercise using .Net Core 3.0 (minute 01:04) and the subsequent error (minute 15:40). Before I opened this issue, I tried very hard to make certain it was an issue.
> 
> I have run into this same problem with the latest 9.1 preview package. When I run after a rebuild, it fails. When I restart the execution, the control renders. Restart again, fails. Restart again, renders. It basically works 50% of the time.
> 
> If I roll back to 7.1 things work fine.
> 
> I tried UWP application with types, and a UWP Class Library. Both with views and user controls. The behavior is the same.
> 
> If anyone has any suggestions, I would really appreciate some guidance here. It's very frustrating to be stuck on an old preview version of the toolkit due to these issues with XamlHost.

I have the exact same issue, followed the instructions carefully [here](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/host-custom-control-with-xaml-islands), the 2019 version.

It fails on "this.InitializeComponent();" of the MyUserControl,   50% of the time. It works, then not, then works, then not.  On-Off.

Using the latest verison of VS2019 - 16.3.5

**Comment by kallidean** [comment]
> What version of Visual Studio 2019 are you using? () We are working with the VS team on making this smoother.

Currently on Visual Studio Professional version 16.4

We are also using MEF for dynamic UI composition, but the XAML Host is referencing the XAMLApplication directly as a project in the same solution.
