### ISSUE TITLE
InkCanvas/Toolbar sample is degraded when Windows' dark theme is selected.

### ISSUE THREAD

**Issue by Lakritzator** [windows-toolkit/Microsoft.Toolkit.Win32#16]
## Current behavior
When starting Microsoft.Toolkit.Win32.Samples.WinForms.App I have a __black__ tab, with the ink toolbar, and can't draw (or see what I am drawing). Also when selecting an item from the toolbar, I expect something like a color selection tool.

## Expected behavior
When starting Microsoft.Toolkit.Win32.Samples.WinForms.App and having the InkCanvas tab selected I expect to be able to draw.

## Minimal reproduction of the problem with instructions
clone this repo, and start the Microsoft.Toolkit.Win32.Samples.WinForms.App

## Environment
Also tried Nuget Package(s): 5.0.1

Windows 10 Build Number:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [x] October 2018 Update (17763)
- [ ] Insider Build (build number: )

App min and target version:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [x] October 2018 Update (17763)
- [ ] Insider Build (xxxxx)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

Visual Studio 
- [x] 2017 (version: )
- [ ] 2017 Preview (version: )
- [x] 2019 Preview (version: 16.0.0 preview 1.1)

Here a screenshot of the app:
![image](https://user-images.githubusercontent.com/708125/50426708-69d18980-0895-11e9-9edc-72b444d4ddef.png)

**Comment by marb2000** [comment]
It seems that there are issues within the Dark theme. Addressing this bug to figure it out what is happening.

**Comment by Lakritzator** [comment]
I finally got to testing the workaround you more or less encoded in your comment: use light mode.
This actually works, which at least allows me to continue working on the feature I was implementing.

**Comment by tigersha** [comment]
Sorry about that, that's right. Technically ink strokes were being drawn, but the color of the pen indicated in the toolbar was black, as was the background. Not obvious, and bad default experience for the sample app when run in dark theme. If you have any questions about the inking feature you're trying to implement, please don't hesitate to reach out to DirectInk at Microsoft dot com.

**Comment by snakechia** [comment]
It has been seven months since this bugs reported, any progress on fixing it?
set the computer to light mode is not the solution, we won't know what is the theme setting for the user in WPF.

**Comment by tigersha** [comment]
You are correct, this does need to work with any system theme. Will look into this; if you are currently blocked one workaround is to change the pen/pencil brush colors from the default (black), to anything other than black/white.

**Comment by marb2000** [comment]
One solution is that the InkCanvas Wrapped control for WPF/WinForms exposes the background color. So app dev cal set the color that they want.  However, the UWP's InkCanvas doesn't have background property. I guess that we should work-around this in the wrapped control.

Meanwhile, this is my suggested workaround for this scenario:

1. Use the WindowXamlHost control with a UWP Grid as XAML Island type. The WindowsXamlHost control is in the NuGet package [Microsoft.Toolkit.Wpf.UI.XamlHost](https://www.nuget.org/packages/Microsoft.Toolkit.Wpf.UI.XamlHost/6.0.0-preview6.4)
```xaml
<Window
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:InkCanvasWrapperWPF"
        xmlns:xamlHost="clr-namespace:Microsoft.Toolkit.Wpf.UI.XamlHost;assembly=Microsoft.Toolkit.Wpf.UI.XamlHost"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">
    <Grid>
         <xamlHost:WindowsXamlHost Grid.Row="1"
            InitialTypeName="Windows.UI.Xaml.Controls.Grid" 
            ChildChanged="WindowsXamlHost_ChildChanged" />

    </Grid>
</Window>
```
2. In the code behind, create the InkCanvas and InkToolbar. The InkCanvas is wrapped by a Grid with the White color as background. The other grid is just for layout proposals.

```cs
 private void WindowsXamlHost_ChildChanged(object sender, EventArgs e)
        {
            var grid = (sender as WindowsXamlHost).Child as Windows.UI.Xaml.Controls.Grid;
            if (grid == null) return;

            var gridInkCanvas = new Windows.UI.Xaml.Controls.Grid();
            gridInkCanvas.Background = new Windows.UI.Xaml.Media.SolidColorBrush(Windows.UI.Colors.White);
            var inkCanvas = new Windows.UI.Xaml.Controls.InkCanvas();
            gridInkCanvas.Children.Add(inkCanvas);
            gridInkCanvas.SetValue(Windows.UI.Xaml.Controls.Grid.RowProperty, 1);

            var inkToolbar = new Windows.UI.Xaml.Controls.InkToolbar();
            inkToolbar.TargetInkCanvas = inkCanvas;
            inkToolbar.SetValue(Windows.UI.Xaml.Controls.Grid.RowProperty, 0);

            var firstRow = new Windows.UI.Xaml.Controls.RowDefinition();
            firstRow.Height = new Windows.UI.Xaml.GridLength(1, Windows.UI.Xaml.GridUnitType.Auto);
            var secondRow = new Windows.UI.Xaml.Controls.RowDefinition();
            secondRow.Height = new Windows.UI.Xaml.GridLength(1, Windows.UI.Xaml.GridUnitType.Star);
            grid.RowDefinitions.Add(firstRow);
            grid.RowDefinitions.Add(secondRow);

            grid.Children.Add(gridInkCanvas);
            grid.Children.Add(inkToolbar);
        }
```

**Comment by michael-hawker** [comment]
Sounds like we need an extra property on InkCanvas to support this.  @Lakritzator can you open a request on the [WinUI](https://aka.ms/winui) for this issue?
