### ISSUE TITLE
XAML Islands targets forces rebuild the solution per every change

### ISSUE THREAD

**Issue by azchohfi** [windows-toolkit/Microsoft.Toolkit.Win32#161]
## I'm submitting a...
- Bug report (I searched for similar issues and did not find one)

## Current behavior
Using Xaml Islands forces me to rebuild the solution every change I do. Simply pressing F5 on VS 2019 16.2.0 does not update the assembly with the new code changes.

## Expected behavior
F5 from VS works and a full rebuild is not required to see a change in either the WinForms/WPF App or the Xaml Island itself.

## Minimal reproduction of the problem with instructions
Add UWP Project referenced by a WPF project, which hosts a Xaml Island with a custom control. Make a simple change, like changing the background color of the custom control.

## Environment
```
Nuget Package(s): Microsoft.Toolkit.Win32.UI.XamlApplication

Package Version(s): 6.0.0-preview7

Windows 10 Build Number:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [X] Insider Build (build number: 18950)

App min and target version:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [ ] October 2018 Update (17763)
- [X] May 2019 Update (18362)
- [ ] Insider Build (xxxxx)

Device form factor:
- [X] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

Visual Studio 
- [ ] 2017 (version: )
- [ ] 2017 Preview (version: )
- [ ] 2019 (version: 16.2.0)

```

**Comment by marb2000** [comment]
@azchohfi and @ocalvo  Did we fix this issue?

**Comment by marb2000** [comment]
It seems that the PR to fix this was merged into the master, so closing the bug.
