### ISSUE TITLE
Transparency around control with rounded corners does not work in WindowsXamlHost

### ISSUE THREAD

**Issue by hansmbakker** [windows-toolkit/Microsoft.Toolkit.Win32#168]
## I'm submitting a...
- Bug report (I searched for similar issues and did not find one)

## Usecase and Context
I am trying to achieve the following:
- application that is triggered from systray / notification area
- upon triggering, a "windowless" UWP XAML control is shown
- the control should use [background acrylic](https://docs.microsoft.com/en-us/windows/uwp/design/style/acrylic#acrylic-blend-types)
- it would be nice for the control to have rounded corners as in the image below
![image](https://user-images.githubusercontent.com/3463496/63228845-88580c80-c1f9-11e9-8067-b478f272a79d.png)

[Example video of what I'm trying to achieve](https://video.twimg.com/tweet_video/D_fRpA_XoAEidOf.mp4) made by @Niels9001 ([source tweet](https://twitter.com/Niels9001/status/1150618753576685568))

Because of the systray / notification area I believe I'm required to use a win32 host application. I chose WPF because it allows for transparent  / chromeless windows.
Because I want to use UWP XAML controls I believe I'm required to use XAML Islands.

## Current behavior
I followed @azchohfi's steps in #159.

I got Acrylic backdrop to work, but when I give the control I want to use rounded corners, **the background behind those corners becomes black instead of transparent** (even though I made the user control background transparent and gave its `Grid` (having the rounded corners) the Acrylic background.

UWP variant:
![UWP-acrylic](https://user-images.githubusercontent.com/3463496/63228715-3b733680-c1f7-11e9-879e-dc0d84a707d3.jpg)

WPF variant:
![WPF-acrylic](https://user-images.githubusercontent.com/3463496/63228716-3c0bcd00-c1f7-11e9-961c-3171082cf90d.jpg)

## Expected behavior
I would expect the background behind the rounded corners to be transparent, especially in the WPF app since I made that app borderless.

## Workarounds I tried:
Because `WindowsXamlHost` seems to draw on its own, it is not affected by any of the following:
- Trying to add a `Border` around the element with rounded corners (WindowsXamlHost draws over the rounded corners)
- Trying to apply a `Clip` property of `RectGeometry` (having set a `RadiusX` and `RadiusY` to `RectGeometry`) to the `Window`, to the `WindowsXamlHost` or another element (the `Window` is clipped but `WindowsXamlHost` draws outside the clipping area)

## Minimal reproduction of the problem with instructions
A bug repro project is available at https://github.com/hansmbakker/AcrylicBackdropWithRoundedCornersBugRepro.

`MyCustomControl` is a simple control with rounded corners and Acrylic backdrop.
- Commit https://github.com/hansmbakker/AcrylicBackdropWithRoundedCornersBugRepro/commit/7cd753c1a9598fdda4ba8038e66a3d0dab52e257 has the plain UWP app.
- Commit https://github.com/hansmbakker/AcrylicBackdropWithRoundedCornersBugRepro/commit/3fc5e413d20808d27c9f3eea21937bcd58a89164 wraps `MyCustomControl` in a transparent and borderless WPF window.

## Environment

```
Nuget Package(s): Microsoft.Toolkit.Wpf.UI.XamlHost, Microsoft.Toolkit.Win32.UI.XamlApplication

Package Version(s): 6.0-preview7.1

Windows 10 Build Number:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [x] Insider Build (18362)

App min and target version:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [x] Insider Build (18362)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

Visual Studio 
- [x] 2019 16.3 Preview 2

```

**Comment by hansmbakker** [comment]
Mentioning @ocalvo as a suggestion from @azchohfi in https://github.com/windows-toolkit/Microsoft.Toolkit.Win32/issues/159#issuecomment-517049613.

**Comment by hansmbakker** [comment]
@azchohfi you also mentioned [trying a c++/win32 app](https://github.com/windows-toolkit/Microsoft.Toolkit.Win32/issues/159#issuecomment-517049613). Does that support the usecase explained above? Why do you think that might be easier?

**Comment by azchohfi** [comment]
@marb2000 or @ocalvo is this scenario supported?

**Comment by marb2000** [comment]
Transparency background is not supported in UWP XAML hence not supported on XAML Islands.

**Comment by hansmbakker** [comment]
Ok, then I won’t use rounded corners there. Thank you for clearing this up.

Could you or @LyalinDotCom (WinUI) comment on whether something like this is on the roadmap?

@niels9001 this outcome can be interesting for you to know what is and is not possible now.

**Comment by hansmbakker** [comment]
@marb2000 done in https://github.com/microsoft/microsoft-ui-xaml/issues/1247
