### ISSUE TITLE
Does Not Support .NET Core 3

### ISSUE THREAD

**Issue by deanchalk** [windows-toolkit/Microsoft.Toolkit.Win32#17]
According to the Microsoft Docs here 
 
https://blogs.msdn.microsoft.com/dotnet/2018/12/04/announcing-net-core-3-preview-1-and-open-sourcing-windows-desktop-frameworks/

One of the key advantages of .NET Core 3 for WPF is its support for XAML islands, which is available via the code in this repository.
However, the code in this repository is not compatible with .NET Core 3, so either the docs are wrong, or this is a regression, or this is now a feature request.

Does anyone have any insight into this?

## I'm submitting a...

  
Feature request (UserVoice request: )

## Environment

```
Nuget Package(s): 

Package Version(s): 

Windows 10 Build Number:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [ ] Insider Build (build number: )

App min and target version:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [ ] Insider Build (xxxxx)

Device form factor:
- [ ] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

Visual Studio 
- [ ] 2017 (version: )
- [ ] 2017 Preview (version: )

```

**Comment by azchohfi** [comment]
We have a branch with partial support, but it's a work in progress:
https://github.com/windows-toolkit/Microsoft.Toolkit.Win32/tree/islandsnetcore30
And the PR is already in place:
https://github.com/windows-toolkit/Microsoft.Toolkit.Win32/pull/7

**Comment by deanchalk** [comment]
@azchohfi - thanks for the update

**Comment by azchohfi** [comment]
You cannot reference the package at all from a dotnet core app. The new PR introduces multitargetting for mostly all projects here, so the same NuGet package will target NetCore3.

**Comment by marb2000** [comment]
Meanwhile, and just for testing proposals, you can find a version of the NuGet packages here: https://www.myget.org/F/miguelrb/api/v3/index.json

**Comment by azchohfi** [comment]
The PR is merged and we should ship a preview version of the packages soon. I'll leave this open for now.

**Comment by TheFanatr** [comment]
I am having trouble using the `6.0.0-preview1` version of the `Microsoft.Toolkit.Wpf.UI.Controls.WebView` package on WPF for .NET Core 3.0 Preview 2. The other packages work correctly as far as I can tell, but I cannot seem to gain access to the `WebView` control supposedly contained within this one. I am using very simple markup, and am unsure why it does not want to compile. The `WebView` component was also not available via Intellisense.
```xaml
<Window x:Class="WpfApp1.MainWindow"
        ...
        xmlns:webview="clr-namespace:Microsoft.Toolkit.Win32.UI.Controls;assembly=Microsoft.Toolkit.Wpf.UI.Controls.WebView"
        ...>
    <Grid>
        <webview:WebView/>
    </Grid>
</Window>
```
Am I doing something wrong?

**Comment by michael-hawker** [comment]
We've tested XAML Islands on .NET Core 3 for the 6.0 release, so closing this issue.
