### ISSUE TITLE
Acrylic backdrop using Xaml Islands only works after re-focus

### ISSUE THREAD

**Issue by hansmbakker** [windows-toolkit/Microsoft.Toolkit.Win32#170]
## I'm submitting a...
- Bug report (I searched for similar issues and did not find one)

## Usecase and Context
I am trying to achieve the following:
- application that is triggered from systray / notification area
- upon triggering, a "windowless" UWP XAML control is shown
- the control should use [background acrylic](https://docs.microsoft.com/en-us/windows/uwp/design/style/acrylic#acrylic-blend-types)
- it would be nice for the control to have rounded corners as in the image below
![image](https://user-images.githubusercontent.com/3463496/63228845-88580c80-c1f9-11e9-8067-b478f272a79d.png)

[Example video of what I'm trying to achieve](https://video.twimg.com/tweet_video/D_fRpA_XoAEidOf.mp4) made by @Niels9001 ([source tweet](https://twitter.com/Niels9001/status/1150618753576685568))

Because of the systray / notification area I believe I'm required to use a win32 host application. I chose WPF because it allows for transparent  / chromeless windows.
Because I want to use UWP XAML controls I believe I'm required to use XAML Islands.

## Current behavior
Using an UWP app, I get Acrylic backdrop **immediately upon the application start**:
![UWP-acrylic](https://user-images.githubusercontent.com/3463496/63382146-68138380-c39a-11e9-87e2-9baeab26b09e.gif)

Using Xaml Islands, I get Acrylic backdrop **only after I unfocus and refocus to the window**:
![XamlIslands-acrylic](https://user-images.githubusercontent.com/3463496/63382165-706bbe80-c39a-11e9-8a00-bdc8ec7fabd3.gif)

I followed @azchohfi's steps in #159.

## Expected behavior

I would expect the Acrylic backdrop to work upon first showing of the window with Xaml Islands.

## Minimal reproduction of the problem with instructions

A repro repository is hosted at https://github.com/hansmbakker/AcrylicFocusBugRepro.
- Commit https://github.com/hansmbakker/AcrylicFocusBugRepro/commit/adc6164a72cfd5f7458bc4f731127cd233c0af16 contains the UWP version.
- Commit https://github.com/hansmbakker/AcrylicFocusBugRepro/commit/e1be1ca1c513ea5a86c4fac9c1c7d9e28d922e96 contains the XAML islands version

The reproduction project is WPF but also affects Windows Forms.

## Environment

```
Nuget Package(s): Microsoft.Toolkit.Wpf.UI.XamlHost, Microsoft.Toolkit.Win32.UI.XamlApplication

Package Version(s): 6.0-preview7.1

Windows 10 Build Number:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [x] Insider Build (18362)

App min and target version:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [x] Insider Build (18362)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

Visual Studio 
- [x] 2019 16.3 Preview 2

```

**Comment by marb2000** [comment]
Unfortunately, this is OS XAML bug that can't fix on the OS. We will address this issue in WinUI 3.

**Comment by dyexlzc** [comment]
I have found the same issue, wondering how to solve it.
![image](https://user-images.githubusercontent.com/38608187/89380332-e727d600-d729-11ea-97f4-7001bf6d518c.png)
![image](https://user-images.githubusercontent.com/38608187/89380352-ee4ee400-d729-11ea-9918-9aaf42bd06fe.png)

**Comment by marb2000** [comment]
Unfortunately, this issues won't be fixed. Perhaps you can force a new Window activation with Window.Activate() or using the Win32 API [SetActivateWindow](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setactivewindow), but I didn't try it by myself.
