### ISSUE TITLE
UWP.UI TabView in .NET Core 3 not at all functional

### ISSUE THREAD

**Issue by doubleyewdee** [windows-toolkit/Microsoft.Toolkit.Win32#171]
## I'm submitting a...
Sample app request 

## Current behavior
.NET Core 3 WPF applications using **Microsoft.Toolkit.Uwp.UI.Controls** cannot use most controls correctly with Xaml Islands. It's unclear from existing documentation whether this is expected to work, though it seems to be implied that you should be able to do this. The NuGet package fails to add XAML resources alongside the placed assembly, and even manually copying them from the NuGet package results in application crashes.

If this is not a supported scenario I think the existing documentation needs to be extremely explicit about **only** supporting wrapped controls.

## Expected behavior
I can make tabs?

## Minimal reproduction of the problem with instructions
See https://github.com/doubleyewdee/netcore3-uwp-ui-test for a trivial example of a .NET Core 3 WPF app attempting to use the most recent (as of issue) NuGet packages for XAML Islands + UWP.UI controls and failing quite badly.

## Environment
Nuget Package(s): 
Package Version(s): 
```xml
<PackageReference Include="Microsoft.Toolkit.Uwp.UI" Version="5.1.1" />
<PackageReference Include="Microsoft.Toolkit.Uwp.UI.Controls" Version="5.1.1" />
<PackageReference Include="Microsoft.Toolkit.Wpf.UI.Controls" Version="6.0.0-preview7.1" />
<PackageReference Include="Microsoft.Toolkit.Wpf.UI.XamlHost" Version="6.0.0-preview7.1" />
```       

Windows 10 Build Number:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [ X] Insider Build (build number: 10.0.18963 N/A Build 18963)

App min and target version:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ X] October 2018 Update (17763)
- [ ] Insider Build (xxxxx)

Device form factor:
- [X ] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

Visual Studio 
- [ ] 2019 (version: )
- [ X] 2019 Preview (version: 16.3.0 Preview2)

**Comment by azchohfi** [comment]
If the controls are not in-box, you need a host UWP project to build the dependencies pri files into something that a Win32 project can use. Just referencing the WCT NuGet packages from your WPF app won't work directly.
We are working on the documentation to make this scenario more clear, but no, you don't need a custom control to host it, but you do need a XAML Application class, which is not provided by your sample.

**Comment by doubleyewdee** [comment]
The scope of "in-box" is very unclear to me here. I would have assumed all of the shipped bits are "in box." Would love to peek at any examples where this works and/or look at docs. I'm a UWP *and* WPF novice so some of the subtle stuff might be escaping me as well.

Thanks!

**Comment by azchohfi** [comment]
In-box mean the controls that come inside the Windows SDK, meaning you don't need to reference anything and they are already loaded (in the context of a UWP application).
The controls inside Microsoft.Toolkit.Uwp.UI.Controls are not in-box, so they require the plumbing I mentioned. You can try to use these steps:
https://github.com/windows-toolkit/Microsoft.Toolkit.Win32/issues/159#issuecomment-517031971

**Comment by doubleyewdee** [comment]
Thanks so much! Following the examples in the referenced issue (and fixing some dumb mistakes on my end) I did get this working. :) I left my very silly / ugly fixed sample in https://github.com/doubleyewdee/netcore3-uwp-ui-test/tree/use-issue-159 mostly for my own benefit.

**Comment by azchohfi** [comment]
Great! I'm glad it worked.
I'm going to close this issue since we do have a few other issues tracking the docs situation.
