### ISSUE TITLE
Windows Application Packaging project crashes after preview7.1 (XAML Islands)

### ISSUE THREAD

**Issue by pcfulife** [windows-toolkit/Microsoft.Toolkit.Win32#175]
## I'm submitting a...

Bug report (I searched for similar issues and did not find one)
 

## Current behavior

Windows Application Packaging (a.k.a. WAP) project crahses after preview6.3
Normal .NET Core 3.0 project doesn't crash.
(I need to package my project because I use Win2D which doesn't run without WAP.)

If I debug WAP project the output says that

> The target process exited without raising a CoreCLR started event. Ensure that the target process is configured to use .NET Core. This may be expected if the target process did not run on .NET Core.
> The program '[14680] XAMLIslandsTest.exe' has exited with code -2147450740 (0x8000808c).

## Expected behavior

WAP project runs well.

## Minimal reproduction of the problem with instructions

[XAMLIslandsTest.zip](https://github.com/windows-toolkit/Microsoft.Toolkit.Win32/files/3584663/XAMLIslandsTest.zip)
This sample project uses preview7.1, but preview6.3/6.4/7.0 has same issue. preview6.2 works well.

## Environment

```
Nuget Package(s): Microsoft.Toolkit.Wpf.UI.XamlHost

Package Version(s): 6.0.0-preview7.1

Windows 10 Build Number:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [x] March 2019 Update (18362)
- [ ] Insider Build (build number: )

App min and target version:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [x] March 2019 Update (18362)
- [ ] Insider Build (xxxxx)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

Visual Studio 
- [ ] 2017 (version: )
- [ ] 2017 Preview (version: )
- [x] 2019 (version: 16.2.4)

```

**Comment by michael-hawker** [comment]
@marb2000 @ocalvo?

**Comment by marb2000** [comment]
I couldn't repro this bug on the latest builds. I rebuilt the solution targetting x64 and running from the WAP.  

Visual Studio: 16.3.0 Preview 3.0.
OS Version:  Windows 10.0.18362
.NET Core: 3.0.100-rc1-014129

Recommendation:  Wait for the final version of .NET Core 2 and VS 2019 Preview 4 or use the latest preview builds.

**Comment by pcfulife** [comment]
@marb2000 After upgrading to VS 16.3.0 Preview 4.0, it runs well. Thanks!
