### ISSUE TITLE
[Question] Can UWP controls written in c# be used in Win32 App using XamlIsland?

### ISSUE THREAD

**Issue by HppZ** [windows-toolkit/Microsoft.Toolkit.Win32#179]
Can UWP controls written in c# be used in Win32 App using XamlIsland?

**Comment by Lechus** [comment]
just type in google: XamlIslands in WPF or Winforms?

**Comment by HppZ** [comment]
Thanks, but what I want is use UWP controls written in c#/xaml in Win32 Apps written in C++. the article you mentioned is about WPF and WinForms.

**Comment by azchohfi** [comment]
Yes, they can be used with Win32 apps:
https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/using-the-xaml-hosting-api

**Comment by HppZ** [comment]
There is no c#/xaml controls being used in Win32 App, I think. Is this scenario really supported? @azchohfi

**Comment by azchohfi** [comment]
It is. @marb2000, do you have a sample in hand?

**Comment by marb2000** [comment]
No so far. This is an untested scenario. There was a regression that avoids consuming a managed WinRT Component in C++/WinRT/CX. It seems that now is possible but in the context of UWP. We need to test it in the context of XAML Islands:  that works on UWP doesn't guarantee it works on Win32. I don't have an ETA yet. I need to adjust the plan.
