### ISSUE TITLE
Expose OSVersionHelper

### ISSUE THREAD

**Issue by onovotny** [windows-toolkit/Microsoft.Toolkit.Win32#18]
Please make `OSVersionHelper` and related enum types public:

https://github.com/windows-toolkit/Microsoft.Toolkit.Win32/blob/master/WebView.Shared/Interop/OSVersionHelper.cs

These can be useful helpers to people who might need to do similar things and they should not need to copy all of the interop code.

**Comment by azchohfi** [comment]
@rjmurillo Do you see any concern about doing this?
The only actual work would be to document a few things that right now are not documented, but I'm ok with it.

**Comment by rjmurillo** [comment]
It's part of the bigger library, so if you wanted to use it you'd bring the library as well. Doubt you'd want to make a lib just for this, though we could probably split is out as a NuGet that includes the source so you could do whatever you wanted.

**Comment by onovotny** [comment]
I took this code and made my own library...though that puts the cost of maintenance on me :)

https://github.com/onovotny/OSVersionHelper

I did add in a couple extra API's like `HasPackageIdentity` (https://github.com/onovotny/OSVersionHelper/blob/master/OSVersionHelper/WindowsVersionHelper.cs#L116), and updated the enums/versions to detect the October2018 and Server 2019 products.

**Comment by azchohfi** [comment]
If anyone needs this, I recommend using @onovotny's library.
