### ISSUE TITLE
Referencing same nuget from .net core and uwp lib

### ISSUE THREAD

**Issue by jasonwurzel** [windows-toolkit/Microsoft.Toolkit.Win32#183]
## I'm submitting a...
 - Bug report (kind of)

## Current behavior
Imagine the following common scenario: 
- The usual "XamlIsland" setup as per the [Docs](https://docs.microsoft.com/en-US/windows/apps/desktop/modernize/host-custom-control-with-xaml-islands): 
  - uwp app
  - .net core wpf app
  - uwp lib containing some user controls (aka "ClassLibrary1")
- now there's also a .net core lib that is referenced from the wpf app (aka "CoreLib")

If I now reference the same nuget package from "CoreLib" and as well from "ClassLibrary1" that has differences for .net core and uwp, like ReactiveUI, I run into trouble. Which version is copied into the output folder and loaded by the wpf app? If it is the uwp flavor of the nuget package, all is well, if it is the .net core flavor, I get runtime exceptions. 

Why? 

Because the uwp version contains uwp specific references (like usage of the UI Dispatcher), that the .net core version does not contain. 
ReactiveUI serves as a nice example but the problem of course is not limited to RxUI but concerns any nuget library that is not completely same for .net core and uwp.

## Expected behavior
Good question, right now our solution is to modify the wpf app csproj to copy the uwp version of ReactiveUI. BUT: As it is now, UWP RxUI is like a superset of .net core RxUI (because of the added UI functionality as mentioned above). If there would also be something in .net core RxUI that is not part of UWP RxUI, there would be no solution to the problem (only intersecting comonalities, so which version should be used at runtime?). 

## Minimal reproduction of the problem with instructions

https://github.com/jasonwurzel/XamlIslandNugetFlavors

clone, build, and start WpfApp1.

observer the "TypeLoadException" because the copied dlls of ReactiveUI and transitively System.Reactive is the .net core one, Dispatcher.Observable is missing.

```
System.TypeLoadException: 'Could not load type 'System.Reactive.Linq.DispatcherObservable' from assembly 'System.Reactive, Version=4.1.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263'.'
```

## Environment

```
Nuget Package(s): 
minor info: used RxUI 9.18.2 because of some XamlIsland-related bug that is not related to this discussion here

```

**Comment by michael-hawker** [comment]
@ocalvo @marb2000 any thoughts?

**Comment by ocalvo** [comment]
You cannot mix libraries that target .Net Core 3.0 and UWP in the same WPF project.
Please change the  .net core library project to a UWP library project.

Please report back if this workaround does not work for you.

**Comment by jasonwurzel** [comment]
Sorry, but that does not resolve the problem. Imagine having the nuget package referenced from a) the UWP lib and b) directly from the (.net core) WPF app. Same problem. 
Please see my updated repo for this example ( https://github.com/jasonwurzel/XamlIslandNugetFlavors )
I'm aware (guessing) that this kind of a midterm problem (comming .net 5 this should resolve itself?) but I wanted to know your opinion about it. 
As for switching to UWP lib project: That is no possibility for us, as XamlIsland was exactly the solution to our problem: breaking out of the uwp sandbox and using the much faster .net core i.e. for file operations etc. 
Plus, as mentioned our solution works but feels (and is) pretty hacky. And as I said above, what if one targetframework (uwp package) is not a superset of the other (.net core)...
I just wanted to raise your awareness to this problem. So I think this Issue should not be closed as it is completely unresolved.

**Comment by jasonwurzel** [comment]
Hi @ocalvo , @marb2000 , @michael-hawker  , I don't want to be a nag but what are your thoughts on the above problem? As I have shown, it is of concern to all "XamlIsland" projects mixing UWP + WPF .net core. Or do you think the likelihood of that situation happening in the wild is small enough that it needs not be adressed?

**Comment by michael-hawker** [comment]
@marb2000 looks like this scenario may have been overlooked?  Or is the guidance here going to have to be to wait until WinUI 3 or something?

Re-opening this issue as it sounds like the root scenario isn't addressed.  Thanks for the extra details @jasonwurzel.

**Comment by marb2000** [comment]
@jasonwurzel Agree that this is super hacky in system XAML Islands, and it's no going to have a better solution. In WinUI 3 project types and references should be easier because at some point all the projects will be .NET 5/6 (except the C++/WinRT ones, of course) using the SDK style project. 

Hope this helps.
