### ISSUE TITLE
Video Playback Sample with Memory Stream with MediaPlayerElement

### ISSUE THREAD

**Issue by samdubey** [windows-toolkit/Microsoft.Toolkit.Win32#186]
## I'm submitting a...

  
 
Sample app request

## Current behavior

I am using BoxedApp or some third-party library to play video using memory stream/byte array
I want to use MediaPlayerElement which has MediaStreamSource support which I want to use for streaming video playback (.mp4 locally).

Please let me know if i could use this MediaPlayerElement from Xaml Islands only in Windows 10 or all Windows Versions?

Please provide sample or guidance to achieve the above functionality.

Thank you.

## Environment

```
Nuget Package(s): 

Package Version(s): 

Windows 10 Build Number:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [ ] Insider Build (build number: )

App min and target version:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [ ] Insider Build (xxxxx)

Device form factor:
- [ X] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

Visual Studio 
- [ ] 2017 (version: )
- [ ] 2017 Preview (version: )

```

**Comment by marb2000** [comment]
@samdubey I'm sorry Nobody helped you with this questions. I guess that you already know the answer now, but just to clarify one of your questions: XAML Islands only works in Windows 10 1903 and adobe. Actually, XAML Islands in in maintenance mode given all the efforts are in [WinUI 3](https://microsoft.github.io/microsoft-ui-xaml/) (for UWP and Desktop) that will contain Islands in the future.
