### ISSUE TITLE
How to load a 3mf file as MapModel3D to MapControl in WPF?

### ISSUE THREAD

**Issue by tranvyhor** [windows-toolkit/Microsoft.Toolkit.Win32#195]
I have a 3mf file which can be previewed in 3D builder app. But in my demo for WPF it doesn't work. The var  **_myModel_** always be null without any exceptions occured. Codes here:

_var filename = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "116(5).3mf");
var sf = await StorageFile.GetFileFromPathAsync(filename);
 var streamReference = RandomAccessStreamReference.CreateFromFile(sf);
var myModel = await MapModel3D.CreateFrom3MFAsync(streamReference, MapModel3DShadingOption.Default);_

Is it file access issue?

**Comment by marb2000** [comment]
@tranvyhor I'm sorry about nobody couldn't answer your question. Did you solve it?

**Comment by marb2000** [comment]
Closing the question. Reopening it if needed?
