### ISSUE TITLE
"level" not equal in different manifest snippets

### ISSUE THREAD

**Issue by tranvyhor** [windows-toolkit/Microsoft.Toolkit.Win32#198]
## I'm submitting a issue
Fail to compile when set **requestedExecutionLevel** to _requireAdministrator_ in app.manifest.
Error occurs as _"level" not equal in different manifest snippets_. My code is a WPF Core3.0 demo by referenced XamlHost.

## Environment
.NET Core 3.0

Nuget Package(s): 
Microsoft.Toolkit.Wpf.UI.XamlHost

Package Version(s): 
6.0.0-preview9.1

Windows 10 Build Number:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [x] Insider Build (build number:18362)

App min and target version:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [x ] October 2018 Update (17763)
- [ ] Insider Build (xxxxx)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

Visual Studio 
- [x] 2019 (version: )

```

**Comment by michael-hawker** [comment]
@marb2000 any thoughts on this?

**Comment by michael-hawker** [comment]
@marb2000 @ocalvo any ideas on this?

**Comment by Kyaa-dost** [comment]
@marb2000 @ocalvo  ⬆️

**Comment by marb2000** [comment]
At this point I will mark this bug as Won't fix. All the efforts are right now on WinUI 3 and this bug doesn't meet the bar.
