### ISSUE TITLE
Add a textbox/richeditbox wrapper to easy to use handwritingview

### ISSUE THREAD

**Issue by pengzh0928** [windows-toolkit/Microsoft.Toolkit.Win32#2]
## I'm submitting a...

  
Feature request (UserVoice request: )

## Current behavior

Haven't a sample for HandWritingView in textBox on XamlIsland.

## Expected behavior

Have an easy sample like MapControl/InkCanvas in XamlIsland sample app.

## Environment

```
Nuget Package(s): 
Microsoft.Toolkit.Forms.UI.XamlHost
Microsoft.Toolkit.Wpf.UI.XamlHost

Package Version(s): 

Windows 10 Build Number:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [x] October 2018 Update (17763)
- [ ] Insider Build (build number: )

App min and target version:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [x] October 2018 Update (17763)
- [ ] Insider Build (xxxxx)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

Visual Studio 
- [x] 2017 (version: )
- [ ] 2017 Preview (version: )

**Comment by marb2000** [comment]
Let's hold this proposal. Before that, we should make sure that the controls and the hosts we have right now are working with enough quality in the first release of Xaml Islands (19H1 timefrime). Does make sense?

**Comment by DJDGSFTX** [comment]
Yes, Of course. We fully agree this enhancement will move to next release.

**Comment by marb2000** [comment]
@pengzh0928 Thanks for creating this enhancement. Unfortunately we are no planning to extend the wrapper controls given we consider the WindowsXamlHost should be the path to use UWP/XAML controls inside of WPF/WinForms instead of the wrappes.
