### ISSUE TITLE
[Feature] Mediaplayer - Aspect ratio property is missing?

### ISSUE THREAD

**Issue by Symbai** [windows-toolkit/Microsoft.Toolkit.Win32#202]
## Describe the problem this feature would solve
The Mediaplayer is missing a property for changing aspect ratio in code. With transport controls enabled there is a button on the GUI to properly set aspect ratio (which is sadly off by default so the video is literally always out of screen by default and this button need to be clicked by the user once). However what this button does cannot be done in code yet.

## Describe the solution
I'm not fully aware of how the UWP version works but according to the docs the stretch property of the MediaPlayer (not MediaPlayerElement) should be it: https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/media-playback#resize-and-stretch-video but it's missing:

![image](https://user-images.githubusercontent.com/14368203/68088172-4af83800-fe54-11e9-9ac3-8e24f003f236.png)

## Describe alternatives you've considered
Setting stretch property of the MediaPlayerElement wrapper does nothing for it.

## Additional context & Screenshots

![image](https://user-images.githubusercontent.com/14368203/68088268-34061580-fe55-11e9-8979-4e2b6bbd7805.png)

**Comment by michael-hawker** [comment]
@Symbai the [Stretch Property](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.mediaplayerelement.stretch) is on the MediaPlayerElement, not MediaPlayer (the example is confusing, I filed an [issue on the docs](https://github.com/MicrosoftDocs/windows-uwp/issues/2069)).  But it sounds like you tried that anyway and it wasn't working.

Assuming this is WPF, but can you confirm, as that can make a difference?

It looks like it should be bound here: https://github.com/windows-toolkit/Microsoft.Toolkit.Win32/blob/master/Microsoft.Toolkit.Wpf.UI.Controls/MediaPlayerElement/MediaPlayerElement.cs#L60, but it could be not binding properly.

**Comment by Symbai** [comment]
@michael-hawker Thanks for the reply. I've tested it but cannot repro on Winforms. On Winforms the video is automatically fit to the window size respecting the aspect ratio. On WPF however it is out of screen when the video is larger than the window size.

### Winforms:
```
// 
// mediaPlayerElement1
// 
this.mediaPlayerElement1.AreTransportControlsEnabled = true;
this.mediaPlayerElement1.Dock = System.Windows.Forms.DockStyle.Fill;
this.mediaPlayerElement1.Location = new System.Drawing.Point(2, 2);
this.mediaPlayerElement1.Margin = new System.Windows.Forms.Padding(2);
this.mediaPlayerElement1.MinimumSize = new System.Drawing.Size(67, 65);
this.mediaPlayerElement1.Name = "mediaPlayerElement1";
this.mediaPlayerElement1.Size = new System.Drawing.Size(1047, 677);
this.mediaPlayerElement1.Source = "https://mediaplatstorage1.blob.core.windows.net/windows-universal-samples-media/e" +
"lephantsdream-clip-h264_sd-aac_eng-aac_spa-aac_eng_commentary-srt_eng-srt_por-sr" +
"t_swe.mkv";
this.mediaPlayerElement1.TabIndex = 0;
this.mediaPlayerElement1.Text = "mediaPlayerElement1";
```

##### Screenshot:
![image](https://user-images.githubusercontent.com/14368203/68381782-55634c00-014a-11ea-9147-c33666e80f32.png)

### WPF
```
<Window ..............>
    <Grid>
        <controls:MediaPlayerElement
        x:Name="mediaPlayerElement"
        AreTransportControlsEnabled="True"
        Loaded="mediaPlayerElement_Loaded"
        Stretch="Uniform"
        Source="https://mediaplatstorage1.blob.core.windows.net/windows-universal-samples-media/elephantsdream-clip-h264_sd-aac_eng-aac_spa-aac_eng_commentary-srt_eng-srt_por-srt_swe.mkv" />
    </Grid>
</Window>
```

##### Screenshot:
![image](https://user-images.githubusercontent.com/14368203/68381707-349af680-014a-11ea-8156-7923b1396459.png)

**Comment by marb2000** [comment]
@michael-hawker and @Symbai I'm planning to close this bug as won't fix and propose using the WindowXamlHost to host the UWP MediaPlayerElement. It's more work that at least you eliminate a layer calling directly the UWP control. Does it sound good?

**Comment by Symbai** [comment]
@marb2000: No, because using WindowXamlHost and the UWP MediaPlayerElement does not provide the stretch property either, see below. I've followed this guide here: https://docs.microsoft.com/en-us/windows/communitytoolkit/controls/wpf-winforms/windowsxamlhost

![image](https://user-images.githubusercontent.com/14368203/89728473-1e91cd80-da1d-11ea-9f5e-9b6a4a7a471a.png)

Also when closing the application this exception raised:
![image](https://user-images.githubusercontent.com/14368203/89728535-6f092b00-da1d-11ea-92bc-f81c80b27abf.png)

**Comment by michael-hawker** [comment]
@Symbai the `MediaPlayer` class doesn't have a `Stretch` property, it's not a UI Element: https://docs.microsoft.com/en-us/uwp/api/Windows.Media.Playback.MediaPlayer

The `MediaPlayerElement` UI container is what has the `Stretch` property: https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.mediaplayerelement (i.e. The `m` variable you have in your code above.)

I would expect the `ChildChanged` event is firing on the application close to tell you the host is now having a `null` child as the content is unloading, so this is probably expected. You only need that event to wire up the initial control, right @marb2000?

**Comment by Symbai** [comment]
You're right about the stretch property. Regarding the exception when its "probably expected" its not stated in the docs: https://docs.microsoft.com/en-us/windows/communitytoolkit/controls/wpf-winforms/windowsxamlhost

However I'm closing the issue
