### ISSUE TITLE
MediaPlayerElement - Local video can only be played if SOURCE is set in xaml (Warning: Large GIF)

### ISSUE THREAD

**Issue by Symbai** [windows-toolkit/Microsoft.Toolkit.Win32#203]
## Describe the bug
Local video appears only in MediaPlayerElement if the source property is set in xaml. And only when set source in MediaPlayer, not MediaPlayerElement.

Setting source in MediaPlayer however also throws a null exception when there is no source property set in xaml.

## Steps to Reproduce
See GIF below, otherwise:

#### 1
* In XAML:
```
<controls:MediaPlayerElement
x:Name="mediaPlayerElement"
Margin="5"
AreTransportControlsEnabled="True"
Loaded="mediaPlayerElement_Loaded" />
```
* In code:
```
private void mediaPlayerElement_Loaded(object sender, RoutedEventArgs e)
{
    mediaPlayerElement.Source = @"D:\SampleVideo_1280x720_5mb.mp4";
}
```
**=> Not working.**

#### 2

* In XAML change to:
```
<controls:MediaPlayerElement
x:Name="mediaPlayerElement"
Margin="5"
AreTransportControlsEnabled="True"
Loaded="mediaPlayerElement_Loaded"
Source="https://mediaplatstorage1.blob.core.windows.net/windows-universal-samples-media/elephantsdream-clip-h264_sd-aac_eng-aac_spa-aac_eng_commentary-srt_eng-srt_por-srt_swe.mkv" />
```
**=> Not working.**

#### 3
* Revert XAML
* In code change to:
```
private void mediaPlayerElement_Loaded(object sender, RoutedEventArgs e)
{
    mediaPlayerElement.MediaPlayer.Source = MediaSource.CreateFromUri(new Uri(@"D:\SampleVideo_1280x720_5mb.mp4"));
}
```
**=> Not working.**

#### 4
* In XAML change to while keeping code changes from step 3:
```
<controls:MediaPlayerElement
x:Name="mediaPlayerElement"
Margin="5"
AreTransportControlsEnabled="True"
Loaded="mediaPlayerElement_Loaded"
Source="https://mediaplatstorage1.blob.core.windows.net/windows-universal-samples-media/elephantsdream-clip-h264_sd-aac_eng-aac_spa-aac_eng_commentary-srt_eng-srt_por-srt_swe.mkv" />
```
**=> Works.**

## Expected behavior
* Setting MediaPlayerElement.Source in code to a local file opens it without source propert in XAML
* Setting MediaPlayerElement.MediaPlayer.Source in code to a local file opens it without source propert in XAML

## Screenshots
![ezgif com-optimize](https://user-images.githubusercontent.com/14368203/68088569-71b86d80-fe58-11e9-9d8f-cb595548e622.gif)

## Environment
```
NuGet Package(s): 
Microsoft.Toolkit.Wpf.UI.Controls
Package Version(s):  6.0.0-rc1

Project .NET Version:
- [ ] .NET Framework (version: )
- [X] .NET Core 3
- [ ] .NET Core 3.1 Preview (version: )

Windows 10 Build Number:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [X] May 2019 Update (18362)
- [ ] Insider Build (build number: )

App min and target version:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [X] May 2019 Update (18362)
- [ ] Insider Build (xxxxx)

Device form factor:
- [X] Desktop
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

Visual Studio 
- [ ] 2017 (version: )
- [X] 2019 (version: ) 16.3.7
- [ ] 2019 Preview (version: )

```

**Comment by michael-hawker** [comment]
@marb2000 @ocalvo would this be the UWP sandbox here?  The MediaPlayerElement is still a UWP control, so it doesn't have access to the local path, right?

**Comment by marb2000** [comment]
There is no AppContainer in XAML Islands. @Austin-Lamb or @AdamBrMSFT, any thought?  it seems to me like a bug.

**Comment by Symbai** [comment]
FYI: I cannot repro this on Winforms. On Winforms setting the `MediaPlayerElement.Source` property to a local file in the `Form_Load` event works perfectly. So this seems to be an WPF issue.

**Comment by marb2000** [comment]
@Symbai good observation. The WPF and WinForms wrapped controls assign the Source property in different ways. @ocalvo can you add this to your backlog?

**Comment by marb2000** [comment]
@Symbai I hope you could workaround this issue. I'm going to close this issue as won't fix for XAML Islands v1. If you couldn't workaround it still persists I recommend to use the WindowXamlHost and host the media player control, so you don't have to use any wrapper control.
