### ISSUE TITLE
WindowsXamlHost TextBox in ContentDialog Ignores characters

### ISSUE THREAD

**Issue by aquinn39** [windows-toolkit/Microsoft.Toolkit.Win32#209]
## Describe the bug
When editing text inside a TextBox in ContentDialog that is hosted in an XamlHost, the TextBox does not respond to any keys you press with the backspace key being the only exception I've seen so far. Basically, you can press any key on the keyboard and it will not type anything into the TextBox. The only things that I have found to work are the backspace key, pasting from the clipboard and inserting emoji using the emoji picker. I have tried entering text using both a hardware keyboard and the touch keyboard but TextBoxes inside ContentDialogs just ignore them.
So far I have only tried this with WPF and not Windows Forms. I am using the .Net Framework 4.8. Another thing to note is that this issue exists in both Windows 10 1903 and Windows 10 1909.

I have tried this in the latest version (version 6.0.0 at the time of writing this) of the Microsoft.Toolkit.Wpf.UI.XamlHost package and it is still not fixed.

## Steps to Reproduce
1. Create a WPF project.
2. Install the Microsoft.Toolkit.Wpf.UI.XamlHost package.
3. Create a page with a ContentDialog and put a TextBox in the ContentDialog.
4. Create an XamlHost and have it host the created page.
5. Call ShowAsync() on the ContentDialog and try to type text into the TextBox that's in the ContentDialog.

## Expected behavior
You should be able to type text into a TextBox that is inside a ContentDialog.

## Screenshots
An example of the setup that produces the bug (TextBox inside ContentDialog)
![image](https://user-images.githubusercontent.com/43898231/69613655-098b2f00-1086-11ea-9ba9-3c6e591ab4c4.png)

## Environment

```
NuGet Package(s): Microsoft.Toolkit.Wpf.UI.XamlHost

Package Version(s): 6.0.0

Project .NET Version:
- [x] .NET Framework (version: 4.8)
- [ ] .NET Core 3
- [ ] .NET Core 3.1 Preview (version: )

Windows 10 Build Number:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [x] May 2019 Update (18362)
- [x] November 2019 Update (18363)
- [ ] Insider Build (build number: )

App min and target version:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [x] May 2019 Update (18362)
- [ ] Insider Build (xxxxx)

Device form factor:
- [x] Desktop
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

Visual Studio 
- [ ] 2017 (version: )
- [x] 2019 (version: 16.3.8) 
- [ ] 2019 Preview (version: )

```

## Additional context
This issue has been reported before but it was marked as resolved, yet the issue still seems to exist in the latest version of the package (6.0.0) and in the latest release of Windows (1909). https://github.com/windows-toolkit/Microsoft.Toolkit.Win32/issues/94

**Comment by niels9001** [comment]
I'm still experiencing this issue.

Windows version: Windows 10 Pro, 2004 (19041.172)

Any updates on this? @marb2000 #94 

Example: 

![image](https://user-images.githubusercontent.com/9866362/78991257-d29b4e80-7b38-11ea-9d50-71b9711c3b6f.png)


`  <ContentDialog
        x:Name="KeyRemapDialog"
        Title="Remap a key"
        PrimaryButtonText="Save"
        CloseButtonText="Cancel"
        DefaultButton="Primary">

            <StackPanel VerticalAlignment="Stretch" HorizontalAlignment="Stretch" Spacing="12" Orientation="Horizontal">
                <ComboBox Header="Original key" IsEditable="True" ItemsSource="{x:Bind KeyStrokes}" Width="200"/>

                <TextBox Width="200"/>
                <ComboBox Header="New key" IsEditable="True" ItemsSource="{x:Bind KeyStrokes}" Width="200"/>
            </StackPanel>
        </ContentDialog>`

Result:
![XAMLhostbug](https://user-images.githubusercontent.com/9866362/78991193-abdd1800-7b38-11ea-845f-4350c16bd67d.gif)

**Comment by marb2000** [comment]
I can repro this bug as well. @Austin-Lamb  and @ocalvo  for awareness.

**Comment by Austin-Lamb** [comment]
@aquinn39 and @niels9001 - thanks for reporting this issue!  We have determined this is a bug in the core part of XAML that lives in the OS.  We don't plan to fix this in OS XAML as the team is putting all of our investments into WinUI 3 instead.

We will target fixing this in WinUI 3.  In the meantime, the only recommendation I have is to consider showing your own Popup and put the TextBox in there.  The bug is specific to ContentDialog when it is used in a Win32 process.
