### ISSUE TITLE
XAML Islands dependencies cause forced rebuilds

### ISSUE THREAD

**Issue by sbanni** [windows-toolkit/Microsoft.Toolkit.Win32#214]
1. Create a new WPF (.NET Core) project
2. Build -> Build Solution (builds)
3. Build -> Build Solution (doesn’t rebuild, since it’s up to date).
4. Add Microsoft.Toolkit.Wpf.UI.Controls and/or Microsoft.Toolkit.Wpf.UI.XamlHost NuGet package as a dependency of the project.
5. Build -> Build Solution (builds)
6. Build -> Build Solution - BUILDS AGAIN

**Comment by sbanni** [comment]
This is because [the up-to-date check is being disabled](https://github.com/windows-toolkit/Microsoft.Toolkit.Win32/blob/master/Microsoft.WinRT.Win32.targets#L10)

**Comment by osolo** [comment]
Hi, there hasn't been any update on this for almost 3 months.  Are there plans to fix the problem?

**Comment by marb2000** [comment]
@sbanni already resolved the bug.

**Comment by sbanni** [comment]
> @sbanni already resolved the bug.
@marb2000 This is not resolved, the targets file is still disabling the fast up to date check and this will still happen.

**Comment by marb2000** [comment]
Ups! My bad. Reopening again and market as external given is a tooling thing.

**Comment by sbanni** [comment]
@marb2000 This targets file is coming from this toolkit, how is that external?

**Comment by marb2000** [comment]
@Austin-Lamb  for awareness

**Comment by marb2000** [comment]
Waiting for @ocalvo confirmation that the problem was solved with the 6.1.1 update.

**Comment by ocalvo** [comment]
<DisableFastUpToDateCheck>true</DisableFastUpToDateCheck> must be added by hand to the Net 5 project.

**Comment by marb2000** [comment]
After talking to @ocalvo, this is something we can't do it automatically in XAML Islands v1 and .NET Core 3.1 because of way the MSBuild targets are designed. However, this won't be an issue in WinUI 3. So closing this issues as Won't Fix and as a workaround set the DisableFastUpToDateCheck to true.

**Comment by osolo** [comment]
@marb2000 @ocalvo I just tried the proposed workaround and it doesn't work.  The WPF project still builds every time.  

I tried with both Visual Studio 16.6.5 and 16.8.0 Preview 2.
