### ISSUE TITLE
Xaml Islands - Microsoft starter example not working for me

### ISSUE THREAD

**Issue by sbanni** [windows-toolkit/Microsoft.Toolkit.Win32#215]
I am following the basic starter example shown here: https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/host-custom-control-with-xaml-islands

I have followed it as closely as I can. I can get it working if I put my user control in with the UWP app (different to the example) but not as it is with the usercontrol in the class library.

Firstly, when I run the example as it is, I get: “WindowsXamlManager and DesktopWindowXamlSource are supported for apps targeting Windows version 10.0.18226.0 and later. Please check either the application manifest or package manifest and ensure the MaxTestedVersion property is updated.”

The only solution I can find to this was to add a manifest file to the wpf project containing:

<?xml version=“1.0” encoding=“utf-8”?>

<assembly manifestVersion=“1.0” xmlns=“urn:schemas-microsoft-com:asm.v1”>

<compatibility xmlns=“urn:schemas-microsoft-com:compatibility.v1”>

<application>

<maxversiontested Id=“10.0.18362.0”/>

<supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}" />

</application>

</compatibility>

</assembly>

After that, I did not see that error, but when the wpf form loads, I see “Cannot create control of type ClassLibrary1.MyUserControl1”, but no clues as to why.

I notived that although I had set x64 for all the projects in the config manager, my solution platform was still set to “any cpu”. I changed it to x64 and then get a different problem, in this. InitializeComponent, "Windows.UI.Xaml.Markup.XamlParseException: ‘XAML parsing failed.’ "

But no information about what has failed or how to solve it.

**Comment by michael-hawker** [comment]
@marb2000 any thoughts here?

**Comment by michael-hawker** [comment]
@sbanni can you check the documentation again, I know they've been trying to keep it up to date.

There's also a link to the full samples at the bottom of the article: https://github.com/microsoft/Xaml-Islands-Samples

**Comment by stuart73** [comment]
I was having the same error “Cannot create control of type ClassLibrary1.MyUserControl1"

 However, after investigation I found the problem was because I was missing this step from the example:-

11 : In the UWP app project you configured earlier, right-click the References node and add a reference to the UWP class library project.

After adding this reference everything worked for me...
