### ISSUE TITLE
Intellisense problems when XamlHost is installed and a UWP application is referenced

### ISSUE THREAD

**Issue by sbanni** [windows-toolkit/Microsoft.Toolkit.Win32#216]
Create three projects:
-   (A)- .Net Core 3.0 WinForms C# project
-   (B)- UWP blank application (set the minimum version to 1903)
-   ©- UWP Class Library (set the minimum version to 1903)

- In (A) add references (B) and ©
- Add a class in (C) (say C.TestClass) with some property, and from a file in (A) instantiate it and try to use automatic completion to access its properties.

Observed: Intellisense works fine

Now, I want to install XamlHost in (A) (since I need Xaml Island).
What I do:

- Remove the references from (A) to both (B) and © (if you don’t do it, XamlHost won’t install in (A) )
- Install XamlHost in (A) to latest version v6.0.0-preview7.1
- In (A) re-add reference to ©

Observed: Intellisense still works for C.TestClass in (A)

- In (A) add reference to the UWP application (B)
- Reload solution (or restart VS)

Observed: Intellisense stops working for C.TestClass in (A) and you can see warning icons on all of the referenced packages and projects

**Comment by marb2000** [comment]
I couldn't repro in VS2019 16.7 so closing it.
