### ISSUE TITLE
[WebView] Detect KeyDown/MouseDown events

### ISSUE THREAD

**Issue by varKeytrap** [windows-toolkit/Microsoft.Toolkit.Win32#221]
Is there anyway of detecting MouseDown or Keyboard down event ? Tried setting those events in WebView and event does't fire (with KeyDown or PreviewKeyDown)

**Comment by varKeytrap** [comment]
Am I supposed to do something ?

**Comment by michael-hawker** [comment]
@varKeytrap you need to add JavaScript events to the page in the WebView and pass key/mouse events up to your application with messaging.  This is a limitation of all the webviews as far as I'm aware.

I'd suggest opening a request on the new [WebView feedback repo](https://github.com/MicrosoftEdge/WebViewFeedback) for a request for this.  It certainly would be a lot easier to do many interop scenarios if they were just hooked up automatically to the native event methods.

FYI @pagoe-msft
