### ISSUE TITLE
App crashes upon closing after using ColorSpectrum/ColorPicker in WindowsXAMLHost

### ISSUE THREAD

**Issue by chanallenk** [windows-toolkit/Microsoft.Toolkit.Win32#222]
## Describe the bug
In a Windows Application Packaging project. (WPF) when using a ColorSpectrum or a ColorPicker with the WindowsXAMLHost, upon closing the application window, an exception occurs:

Exception thrown at 0x00007FFEC8F64553 (threadpoolwinrt.dll) in TestWPF.Core.exe: 0xC0000005: Access violation reading location 0x0000000000000000.

I am resubmitting [this issue](https://github.com/windows-toolkit/Microsoft.Toolkit.Win32/issues/101) because it is still a bug, even with several versions later and following the documentation.

## Steps to Reproduce
1. Create a new XAML island project with a custom control, following the documentation [here ](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/host-custom-control-with-xaml-islands). In the custom control, add a Windows.UI.Xaml.Controls.ColorPicker or Windows.UI.Xaml.Controls.Primitives.ColorSpectrum
2. Launch the application 
3. Interact with the ColorPicker
4. Close the MainWindow, application will crash

## Expected behavior
No errors occur and app closes without issue

## Environment

```
NuGet Package(s): 
1. Microsoft.Toolki.Wpf.UI.XamlHost
2. Microsoft.VCRTForwarders.140

Package Version(s): 
1. v6.0.0
2. v1.0.4

Project .NET Version:
- [ ] .NET Framework (version: )
- [ ] .NET Core 3
- [X] .NET Core 3.1

Windows 10 Build Number:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [ ] May 2019 Update (18362)
- [X] November 2019 Update (18363)
- [ ] Insider Build (build number: )

App min and target version:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [X] May 2019 Update (18362)
- [ ] Insider Build (xxxxx)

Device form factor:
- [X] Desktop
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

Visual Studio 
- [ ] 2017 (version: )
- [X] 2019 (version: 16.4.1) 
- [ ] 2019 Preview (version: )

```

**Comment by michael-hawker** [comment]
@chanallenk Thanks for the report, have you tried the WinUI versions of the controls to see if they encounter the same issue?

FYI @marb2000 @ocalvo.

**Comment by chanallenk** [comment]
@michael-hawker Yes, I just tried using the colorpicker in the latest stable version of WinUI 2 and still getting the same error.

**Comment by KaiDevelopment** [comment]
@chanallenk Did you try to follow the (newly added ?) instructions found under ["Instantiate the XamlApplication object in the entry point of your WPF app"](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/host-custom-control-with-xaml-islands#instantiate-the-xamlapplication-object-in-the-entry-point-of-your-wpf-app)?
That solved the problem for me.

**Comment by chanallenk** [comment]
@KaiDevelopment Thank you, I didn't notice it got updated. It seemed to fix this for me. Still running into a ton of other issues but that's for a separate thread :)
