### ISSUE TITLE
callee is not available WPF WebView

### ISSUE THREAD

**Issue by mjkkirschner** [windows-toolkit/Microsoft.Toolkit.Win32#223]
## Describe the bug

I understand that WebView is being deprecated but I'm trying to understand how to move forward or investigate this exception.

When I instantiate a `WebView` in wpf with a simple application it works great. I am rendering a simple html page with a single button.

But when I attempt to instantiate a `WebView` control in a more complex native application hosting a .net runtime the following exception is raised:

`
The callee (server [not server application]) is not available and disappeared; all connections are invalid. The call may have executed. (Exception from HRESULT: 0x80010007 (RPC_E_SERVER_DIED))
`
at `CreateWebViewControlHostAsync()`

Sometimes instead the exception changes to `call was rejected by callee ' ` ( the single quote is not a typo)

Is this a supported use case? Any advice on how to proceed would be much appreciated.

- [ ] Is this bug a regression in the toolkit?  If so, what toolkit version did you last see it work: (unknown)

## Steps to Reproduce
...

## Expected behavior
I expected to see a simple html page with a button. When I open my sample html in edge it renders correctly. I can also open it with the WebView in a small sample application.

## Environment

```
NuGet Package(s): 

Package Version(s): 

Project .NET Version:
- [x ] .NET Framework (version: 4.8) - project targets 4.7
- [ ] .NET Core 3
- [ ] .NET Core 3.1 Preview (version: )

Windows 10 Build Number:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [x] May 2019 Update (18362)
- [ ] Insider Build (build number: )

(I'm not sure how to find this information)
App min and target version:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [ ] May 2019 Update (18362)
- [ ] Insider Build (xxxxx)

Device form factor:
- [x] Desktop
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

Visual Studio 
- [x] 2017 (version: 15.9.11 )
- [ ] 2019 (version: ) 
- [ ] 2019 Preview (version: )

```

## Additional context
When I switch to `WebBrowser` control the html page renders correctly in the more complex application.

**Comment by baogechen** [comment]
i found this happens in Long-Term Servicing Channel (LTSC) versions of Windows
