### ISSUE TITLE
How to make WebView editable?

### ISSUE THREAD

**Issue by lalitpatil007** [windows-toolkit/Microsoft.Toolkit.Win32#226]
Like WebBrowser, how WebView can be made editable? WebView does not seem to have document property that can be typecasted to IHTMLDocument2 or HTMLDocument (designMode = "On").
Scripting is the only way or is there any better way to make it editable?

Kindly let me know.

Thanks

**Comment by michael-hawker** [comment]
Hi @lalitpatil007 are you talking about modifying the DOM? I believe [that question](https://github.com/MicrosoftEdge/WebViewFeedback/issues/77) has already been asked on the new WebView feedback repo.  They don't plan to expose the DOM directly.  However, feel free to voice your scenario there.

FYI @pagoe-msft

**Comment by lalitpatil007** [comment]
Thanks @michael-hawker . Yes I was referring to modifying DOM.
