### ISSUE TITLE
Add a SwapChainPanel sample for WPF

### ISSUE THREAD

**Issue by mgnslndh** [windows-toolkit/Microsoft.Toolkit.Win32#227]
## Describe the problem this feature would solve
Make it easier for WPF developers to make use of the SwapChainPanel control.

## Describe the solution
Add a sample of how to use the SwapChainPanel control in a WPF app.

**Comment by jdsterli** [comment]
Although there is currently no sample showing how to use UWP's SwapChainPanel in WPF, I am curious if the current preferred way to access it is via WindowsXamlHost, since I do not see it in Microsoft.Toolkit.Wpf.UI.Controls namespace.

**Comment by marb2000** [comment]
The latest official samples using the SwapChainPanel in UWP is [here](https://github.com/microsoft/Xaml-Islands-Samples/blob/c0f357a2b16591001b7796d73f80651f2813cb1a/Standalone_Samples/WinForms_WPF_Core3/UWPApplication/Controls_Pages/MediaPage.xaml.cs#L23).
