### ISSUE TITLE
[Question] .NET Framework add a reference to UWP app project fail

### ISSUE THREAD

**Issue by renchuanming** [windows-toolkit/Microsoft.Toolkit.Win32#232]
hi, i have follow https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/host-standard-control-with-xaml-islands , Create WPF project(.NET framework 4.7.2) and  Blank App (Universal Windows) project
can not success in this step "8. In your WPF project, right-click the Dependencies node and add a reference to your UWP app project." 
![image](https://user-images.githubusercontent.com/49973213/73738903-43606c00-4780-11ea-89ca-c74232dcfc1b.png)

Prompt "Unable to add a reference to project "MyUWPApp""!
Missing something in the documents?or Something I missing?

**Comment by marb2000** [comment]
.NET Framework doesn't support 3rd party scenarios, like referencing a UWP app project. I have sent a PR to fix the documentation.
