### ISSUE TITLE
App crashes because of CreateWinRTRegistration should not put UWP project Packaging Outputs into the CopyToOutputDirectory

### ISSUE THREAD

**Issue by sbanni** [windows-toolkit/Microsoft.Toolkit.Win32#239]
[Sample Project](https://github.com/Lawrence-spt/Xaml-island-build-issue)

The issue is that 'CreateWinRTRegistration' gets run when the packaging project is collecting all the required files from the WpfCoreApplication; 'CreateWinRTRegistration' builds the UWP project and collects all the packaging outputs and puts them into Content items.  These then get copied to the output directory overwriting the WpfCoreApplication dependency files.

When the sample project runs successfully it should just display a blank window, instead it is crashing with these following errors:
1.) Could not load file or assembly 'System.Runtime, Version=4.2.2.0
     1.	Use the package wizard on the ApplicationProject to build a Debug x64 package.
     2.	Install and run the package
     3.	Check the windows Application event log for the error

2.) Could not load type 'System.IAsyncDisposable' from assembly 'System.Runtime, Version=4.2.1.0
     1.	Change the target framework of the WpfCoreApplication to .Net Core 3.0
     2.	Use the package wizard on the ApplicationProject to build a Debug x64 package.
     3.	Install and run the package
     4.	Check the windows Application event log for the error

3.) Could not load type 'System.Windows.Threading.DispatcherObject' from assembly 'WindowsBase
     1.	Ensure the target framework of the WpfCoreApplication is set to .Net Core 3.0
     2.	Use the package wizard on the ApplicationProject to build a Release x64 package.
     3.	Install and run the package
     4.	Check the windows Application event log for the error

If you change the version of the XamlHost package on the WpfCoreApplication project from 6.0.0 to 6.0.0-preview6.4 and repeat the above steps you should no longer see any of those errors when packaging and running the application.

**Comment by michael-hawker** [comment]
@marb2000 @ocalvo thoughts?

**Comment by gcookemoto** [comment]
This still appears to be an issue using the latest version (6.0.1) of the `Microsoft.Toolkit.Wpf.UI.XamlHost` package.  This can be reproduced by upgrading the `Microsoft.Toolkit.Wpf.UI.XamlHost` package in the sample repository above.

We see exactly the same problem in our own XAML islands application, and have also reproduced it in a minimal XAML islands to which we added a use of `Microsoft.Extensions.Hosting`.
