### ISSUE TITLE
Startup time of self-contained .net core apps is noticable longer compared to using the installed version

### ISSUE THREAD

**Issue by lhak** [windows-toolkit/Microsoft.Toolkit.Win32#249]
## Describe the bug

When creating a self-contained .net core app (seems to be the default) the startup time is noticable longer than when using the system-wide installed version (or .net framework). This seems to be caused by the xaml host code loading all dlls from the app directory when looking for metadata.

- [ ] Is this bug a regression in the toolkit?  If so, what toolkit version did you last see it work:

## Steps to Reproduce
1. Create a self-contained version of the app and compare it to using the system-wide installation of .net core

## Expected behavior

There should be probably be a blacklist in the code to not look for metadata in all the .net core dlls.

## Environment

```
NuGet Package(s): 

Package Version(s): 

Project .NET Version:
- [ ] .NET Framework (version: )
- [ ] .NET Core 3
- [X ] .NET Core 3.1 Preview (version: )

Windows 10 Build Number:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [ X] May 2019 Update (18362)
- [ ] Insider Build (build number: )

App min and target version:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [ X] May 2019 Update (18362)
- [ ] Insider Build (xxxxx)

Device form factor:
- [ X] Desktop
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

Visual Studio 
- [ ] 2017 (version: )
- [ X] 2019 (version: ) 
- [ ] 2019 Preview (version: )

```

**Comment by marb2000** [comment]
Thanks for letting this know @lhak. Unfortunately, we can't improve these scenario for XAML Islands v1 at this point, although we will revisit it for WinUI 3.
