### ISSUE TITLE
XAML islands in a classic win32 dll is it possible? Error: hresult_no_interface at memory

### ISSUE THREAD

**Issue by robertsi** [windows-toolkit/Microsoft.Toolkit.Win32#252]
Hi!

I tried to create a standard win32.dll that creates a win32 thread+ window and uses xaml islands.

I debugged the dll....and it fails on 
`auto interop = desktopSource.as<IDesktopWindowXamlSourceNative>();`
with error hresult_no_interface at memory.

![image](https://user-images.githubusercontent.com/3690720/78774679-4b61a580-7995-11ea-8410-16496083ca04.png)

KR,
Robert

**Comment by robertsi** [comment]
Well had to comment out #define WIN32_LEAN_AND_MEAN in framework.h. Should have been mentioned in "Host a standard UWP control in a C++ Win32 app"!!! Code there just happens to work because it deletes the framework.h include...

In general WinRT tooling in 16.5.3 is a headache atm, especially with the usercontrol, viewmodel grouping bug  (https://developercommunity.visualstudio.com/content/problem/959456/item-template-dependent-nesting-behavior-broken-in.html)  ...almost unusable unless you look at github samples and maually edit vcxproj file. Otherwise it was not generating the xaml h. and .cpp files and was randomly renaming them to xaml.h and xaml.cpp. Also not generating stubs foridl files, and generating stubs for already deleted .xaml files). This needs a fix yesterday!

**Comment by azchohfi** [comment]
@marb2000 can you take a look at these to update the docs?

**Comment by robertsi** [comment]
@azchohfi Well It is mentioned in Host a **custom** UWP control in a C++ Win32 app(https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/host-custom-control-with-xaml-islands-cpp), but as I was first trying to get the basics working I was unnecessary scratching my head for a few hours. But a **far bigger issue** was that the wizards for adding items are not working!

Following wizards:
![image](https://user-images.githubusercontent.com/3690720/78935569-4728ab80-7aad-11ea-93e5-46b059acd1ab.png)

produces almost nothing and mess project up.
![image](https://user-images.githubusercontent.com/3690720/78935236-a934e100-7aac-11ea-80b1-8475c764158b.png)
Event viewmodel.idl is not picked up as it generates nothing, then I have to fix it all by manually editing project files, looking at examples in github...

KR,
Robert

**Comment by marb2000** [comment]
It's a Visual Studio regression. I have informed them, waiting for a response.

**Comment by MikeWeller** [comment]
I just ran into this while trying the example on https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/host-standard-control-with-xaml-islands-cpp based on a new project using the "Windows Desktop Application" C++/WinRT template.

As above, I worked around it by adding `#undef WIN32_LEAN_AND_MEAN` at the top of the .pch in the project. Thanks @robertsi !

**Comment by marb2000** [comment]
It seems that #undef WIN32_LEAN_AND_MEAN was causing this issue.
We updated the doc: [https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/host-custom-control-with-xaml-islands-cpp](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/host-custom-control-with-xaml-islands-cpp)
