### ISSUE TITLE
WindowsXamlHost control for Windows Forms Example Not Working

### ISSUE THREAD

**Issue by SPWiggins** [windows-toolkit/Microsoft.Toolkit.Win32#262]
Hi

I am trying to run through the very basic example on the page below, following the instructions for WinForms

[https://docs.microsoft.com/en-us/windows/communitytoolkit/controls/wpf-winforms/windowsxamlhost
](https://docs.microsoft.com/en-us/windows/communitytoolkit/controls/wpf-winforms/windowsxamlhost)

I keep getting errors when trying to drag a WindowsXamlHost control onto the designer

I have been communicating on MSDN forums and this process describes to problem and what I have tried, please see the following link Problem with WinForms [https://social.msdn.microsoft.com/Forums/en-US/993f21f0-2d8a-43ec-9bdc-c42ab4187314/xaml-islands?forum=winforms](https://social.msdn.microsoft.com/Forums/en-US/993f21f0-2d8a-43ec-9bdc-c42ab4187314/xaml-islands?forum=winforms)

Can anyone help please with my problem. I really need to try and get some modern UWP controls into my WinForms program.

I did post on Stack Exchange as advised. Please see following link
[https://stackoverflow.com/questions/61520707/windows-toolkit-xamlhostcontrol-in-winforms](https://stackoverflow.com/questions/61520707/windows-toolkit-xamlhostcontrol-in-winforms)

**Comment by Kyaa-dost** [comment]
@marb2000 any insight on this?

**Comment by marb2000** [comment]
The [doc](https://docs.microsoft.com/en-us/windows/communitytoolkit/controls/wpf-winforms/windowsxamlhost) is no up-to-date and we are going to update it soon. 

Also, there is an issue with the Windows Forms designer in Visual Studio 2019 16.6+  that needs to be debugged:

![image](https://user-images.githubusercontent.com/12536513/89690852-5c2b1500-d8bc-11ea-8f9f-dd38b03bb8fa.png)

Meanwhile, for using WindowXamlHost in WinForms you can do something like:
```CS
public Form1()
        {
            InitializeComponent();

            this.windowsXamlHost1 = new Microsoft.Toolkit.Forms.UI.XamlHost.WindowsXamlHost();
            this.windowsXamlHost1.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowOnly;
            this.windowsXamlHost1.InitialTypeName = "Windows.UI.Xaml.Controls.ColorPicker";
            this.windowsXamlHost1.Location = new System.Drawing.Point(0, 0);
            this.windowsXamlHost1.Name = "windowsXamlHost1";
            this.windowsXamlHost1.Size = new System.Drawing.Size(800, 800);
            this.windowsXamlHost1.TabIndex = 0;
            this.windowsXamlHost1.Text = "windowsXamlHost1";
            this.windowsXamlHost1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.Controls.Add(this.windowsXamlHost1);
        }
        private Microsoft.Toolkit.Forms.UI.XamlHost.WindowsXamlHost windowsXamlHost1;
```
The application will require to set the maxversiontested Id="10.0.18358.0" in the app manifest:
```XML
<compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1">
    <application>
		<maxversiontested Id="10.0.18358.0"/>
    </application>
  </compatibility>
```

Hope this helps. 

Happy XAML coding!
