### ISSUE TITLE
Chrome-based Edge for Microsoft.Toolkit.Forms.UI.Controls.WebView?

### ISSUE THREAD

**Issue by LukeOwlclaw** [windows-toolkit/Microsoft.Toolkit.Win32#268]
The description of the [NuGet package Microsoft.Toolkit.Forms.UI.Controls.WebView](https://www.nuget.org/packages/Microsoft.Toolkit.Forms.UI.Controls.WebView) reads:

> This control uses the Microsoft Edge rendering engine (EdgeHTML)

But ["EdgeHTML" has become "Edge Legacy"](https://support.microsoft.com/en-us/help/4501095/download-the-new-microsoft-edge-based-on-chromium):

> The new Microsoft Edge is based on Chromium and was released on January 15, 2020.

Are there any plans to use Chrome-based Edge for `WebView`?

**Comment by michael-hawker** [comment]
Hi @LukeOwlclaw, there's already a new version in preview, that's all handled by the Edge team directly now, so the code in this repository is deprecated. You can find all the links to docs/repos in our notice on our readme [here](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2). Thanks!
