### ISSUE TITLE
[Question] Should the mouse events work on WebView in WPF?

### ISSUE THREAD

**Issue by atiyka** [windows-toolkit/Microsoft.Toolkit.Win32#297]
I have a WPF (.netcore3.1) application and I'm using the WebView via the package Microsoft.Toolkit.Wpf.UI.Controls.WebView (6.1.2). It displays the html correctly, but I'm not able to catch the mouse events. I tried multiple mouse events, like MouseWheel, PreviewMouseWheel, MouseLeftButtonDown and so on, but none of them is fired when it should be.
I attached the event listener after the html is content loaded with the following code:
`browserView.MouseWheel += Browser_MouseWheel;`

Is this a bug? Or I missed some information?

**Comment by michael-hawker** [comment]
@atiyka I don't think any of the standard events are automatically hooked up for you. You'd have to inject JavaScript to listen to the events from the page? 

@pagoe-msft can correct me if I'm wrong, but it's best to test this out on [WebView2](https://aka.ms/webview2) and file an issue on their repo if it doesn't work as expected.

**Comment by atiyka** [comment]
Thanks for the answer, finally I solved it by using JavaScript.
I also tried the WebView2, but it has lots of bugs and it's almost unusable, so I went back to the previous version. Most of the bugs are already reported in github, but until it'll be fixed, I will use this version.
