### ISSUE TITLE
How can i activate Flash Player for pages when using Forms.UI.Controls.WebView?

### ISSUE THREAD

**Issue by EvilBozkurt** [windows-toolkit/Microsoft.Toolkit.Win32#298]
How can i activate Flash Player for pages when using Forms.UI.Controls.WebView? This is my question iam sorry for this English :D if you dont understand i can help you about this :D

**Comment by michael-hawker** [comment]
[Flash Player is End-of-Life](https://www.adobe.com/products/flashplayer/end-of-life.html) this scenario isn't supported and I assume won't be supported on [WebView2](https://aka.ms/webview2) either. FYI @pagoe-msft. [Microsoft EOL info here](https://docs.microsoft.com/en-us/lifecycle/announcements/adobe-flash-end-of-support)

**Comment by EvilBozkurt** [comment]
> [Flash Player is End-of-Life](https://www.adobe.com/products/flashplayer/end-of-life.html) this scenario isn't supported and I assume won't be supported on [WebView2](https://aka.ms/webview2) either. FYI @pagoe-msft. [Microsoft EOL info here](https://docs.microsoft.com/en-us/lifecycle/announcements/adobe-flash-end-of-support)

Thank you 🙏🏼 so i gave up making a project with Flash Player
