### ISSUE TITLE
[Question] How to properly resize DesktopWindowXamlSource to avoid flicker & jitter

### ISSUE THREAD

**Issue by AzAgarampur** [windows-toolkit/Microsoft.Toolkit.Win32#303]
UWP applications are resizable, and they do not experience the ugly resize jitter & flicker that most classic Win32 applications do. However, I was expecting the same experience while using the XAML hosting API, but it looks like the problem still persists.

Is there a proper way to resize the DesktopWindowXamlSource XAML window so that we can achieve the same clean resize behavior that UWP applications have? This jitter/flicker looks terrible, especially when using HostBackdrop acrylic - its something you'd not expect when rendering XAML controls with animations, shadows, etc.

This question was originally opened here: https://github.com/MicrosoftDocs/windows-uwp/issues/2902, but now is open here.

**Comment by michael-hawker** [comment]
FYI @marb2000

**Comment by marb2000** [comment]
Unfortunately It's a well known issue that it's caused for the current implementation of system DesktopWindowsXamlSource API. There are improvements on the WinUI 3's DesktopWindowsXamlSource API that we are using for scenarios like Desktop WinUI 3, but you won't be able to use it until we release XAML Islands for WinUI 3.
