### ISSUE TITLE
WindowsXamlManager and DesktopWindowXamlSource not supported

### ISSUE THREAD

**Issue by Unknown025** [windows-toolkit/Microsoft.Toolkit.Win32#57]
## I'm submitting a...

Bug report (I searched for similar issues and did not find one)
 

## Current behavior

I have added the NuGet package for "Microsoft.Toolkit.Forms.UI.XamlHost" and added an XamlHost component using the designer view. I did not change any of the default values, and attempted to start the application. It crashes when trying to initialize the XamlHost with the error "WindowsXamlManager and DesktopWindowXamlSource are not supported on releases prior to 10.0.18226.0'". I'm not sure what the version number is referencing. I have updated my SDK and .NET versions to the latest development versions available. (I am also part of the Windows Insiders program, so I am using a preview build and preview SDK.)

## Expected behavior

The application launches without any errors.

## Minimal reproduction of the problem with instructions

Creating a project targeting .NET 4.8, adding the NuGet package, adding the XamlHost component, and running the application.

## Environment

```
Nuget Package(s): 
Microsoft.Toolkit.Forms.UI.XamlHost
Package Version(s): 
5.01
Windows 10 Build Number:
Windows 10 18309.1000 (version 1809)

App min and target version:
Can't find an option to target a specific version of Windows, only .NET (am targeting .NET 4.8, December build)

Device form factor:
WinForms (Desktop)

Visual Studio 
2017 (Version 15.8.5)

**Comment by azchohfi** [comment]
You need to add a app.manifest file and have the maxversiontested. Example
https://github.com/windows-toolkit/Microsoft.Toolkit.Win32/commit/9363094b53a944f15072a437c8faf5b9032ffc06

**Comment by Unknown025** [comment]
That solved my problem, thanks!

**Comment by liquidboy** [comment]
ran into this when setting up my own WPF app with WindowsXamlHost .. for those that add an app.manifest to your WPF app , don't forget to change the csproj file to tell the WinExe to use the manifest  
![image](https://user-images.githubusercontent.com/599657/51795121-89602700-2232-11e9-8537-43af9c82d6df.png)
