### ISSUE TITLE
Cannot add MapElements to MapControl in WinForms

### ISSUE THREAD

**Issue by BobbyCannon** [windows-toolkit/Microsoft.Toolkit.Win32#62]
## I'm submitting a...

Bug report (I searched for similar issues and did not find one)
 

## Current behavior
When adding items to the Map.MapElements collection they will not appear on the map, code works in UWP but not in WinForms.

```
private void Map_MapTapped(object sender, MapInputEventArgs e)
{
	var pushpin = new MapIcon
	{
		Location = e.Location,
		Title = "Here's something interesting!",
		CollisionBehaviorDesired = MapElementCollisionBehavior.RemainVisible,
		NormalizedAnchorPoint = new Point(0.5, 1)
	};

	Map.MapElements.Add(pushpin);

	Debug.WriteLine(Map.MapElements.Count);
}
```

## Expected behavior
I would expect the map element to be added...

## Minimal reproduction of the problem with instructions
* Create new WinForm project
* Add nuget packages
  * Microsoft.Toolkit.Forms.UI.Controls version="5.0.1" targetFramework="net472"
  * Microsoft.Toolkit.Forms.UI.XamlHost version="5.0.1" targetFramework="net472"
* Follow these instructions
  * https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-enhance
* Add MapControl to your main form
* Wire up the provide code above to the MapTapped event

## Environment

```
Nuget Package(s): 

Package Version(s): 

Windows 10 Build Number:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ X] October 2018 Update (17763)
- [ ] Insider Build (build number: )

App min and target version:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [X ] October 2018 Update (17763)
- [ ] Insider Build (xxxxx)

Device form factor:
- [ X] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

Visual Studio 
- [ X] 2017 (version: 15.9.5)
- [ ] 2017 Preview (version: )

```

**Comment by azchohfi** [comment]
This should be fixed in the latest MyGet. Please, test and reopen the issue if it's still a problem.
