### ISSUE TITLE
Microsoft.Toolkit.Win32.UI.Controls NuGet migration to 5.0

### ISSUE THREAD

**Issue by rjmurillo** [windows-toolkit/Microsoft.Toolkit.Win32#64]
## Current behavior

Version 4.0.2 and 4.0.3 are the most popular, with 5.0 releases roughly half the v4. 

## Expected behavior

Include major versioned package that only references the new versions we want people to migrate to as a means to get people to migrate to the new namespace and distributed packages. 

## Environment

```
Nuget Package(s): Microsoft.Toolkit.Win32.UI.Controls

Package Version(s): 4.0.x



Windows 10 Build Number:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [ ] Insider Build (build number: )

App min and target version:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [ ] Insider Build (xxxxx)

Device form factor:
- [ ] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

Visual Studio 
- [ ] 2017 (version: )
- [ ] 2017 Preview (version: )

```

**Comment by azchohfi** [comment]
We've also unlisted the old packages so people stop installing them.

**Comment by azchohfi** [comment]
We just pushed https://www.nuget.org/packages/Microsoft.Toolkit.Win32.UI.Controls/5.0.0

**Comment by rjmurillo** [comment]
@nmetulev This is contrary than what we agreed upon at the onset of this project

**Comment by nmetulev** [comment]
I agree we jumped the gun on this and should not have pushed this so fast - should have waited until there was an agreement.

We shouldn't remove the new package however as that would be very random.
