### ISSUE TITLE
XAML Island plus Microsoft Advertising Banner Control  System.TypeLoadException: Could not find Windows Runtime type Microsoft.Advertising.WinRT.UI.AdControl

### ISSUE THREAD

**Issue by feliceferri** [windows-toolkit/Microsoft.Toolkit.Win32#65]
## I'm submitting a...
Bug report (I searched for similar issues and did not find one) 

## Background
Following https://docs.microsoft.com/en-us/windows/communitytoolkit/controls/wpf-winforms/windowsxamlhost I Successfully created a UWP Class Library, created a UserControl (MyUserControl1) on it, just changed the Grid Background to red. Then on the WPF side:
<XamlHost:WindowsXamlHost x:Name="WindowsXamlHost1"  InitialTypeName="UWPClassLibrary.MyUserControl1"  ChildChanged="WindowsXamlHost1_ChildChanged">

It worked perfectly!!, got Red inside the WindowsXamlHost.

## Current behavior
Problem arises when inside the UserControl (UWP Class Library) I Add the AdControl (Microsoft.Advertising.WinRT.UI - Microsoft.Advertising Library).
For that I follow => https://docs.microsoft.com/en-us/windows/uwp/monetize/install-the-microsoft-advertising-libraries

UWP side compiles perfect, (in fact when I follow the same guide on a UWP App I get the Advertisings).

On the WPF Side though it doesnt compile. I get a (Missing Assembly Reference to the Microsoft.Advertising library), I solve that by adding a reference to  C:\Users\{User}\.nuget\packages\microsoft.advertising.xaml\10.1805.7001\SDK\Windows Kits\10\ExtensionSDKs\Microsoft.Advertising.Xaml\10.0\References\CommonConfiguration\neutral\ Microsoft.Advertising.winmd

Now WPF compiles, but throw a runtime error => System.TypeLoadException: Could not find Windows Runtime type Microsoft.Advertising.WinRT.UI.AdControl

## Expected behavior
Advertising showing in a WPF project thanks to XAML Islands

## Minimal reproduction of the problem with instructions
I prepared this Word Doc that includes all the screenshots
[XAML Islands plus Microsoft Advertising.docx](https://github.com/windows-toolkit/WindowsCommunityToolkit/files/2627480/XAML.Islands.plus.Microsoft.Advertising.docx)

## Environment
Nuget Package(s): 

## On the UWP Class Library
Microsoft.Advertising.XAML 10.1805.7001
Microsoft.NETCore.UniversalWindowsPlatform 6.2.2
UWP Extension => Microsoft Advertising SDK for XAML  C:\Users\User}\.nuget\packages\microsoft.advertising.xaml\10.1805.7001\SDK\Windows Kits\10\ExtensionSDKs\Microsoft.Advertising.Xaml\10.0\

## On the WPF Side
.NET 4.7.2
System.Runtime.WindowsRuntime  C:\Windows\Microsoft.NET\Framework\v4.0.30319

System.Runtime.WindowsRuntime.UI.Xaml  C:\Windows\Microsoft.NET\Framework\v4.0.30319

System.Runtime.InteropServices.WindowsRuntime  C:\Windows\Microsoft.NET\Framework\v4.0.30319

Windows.Foundation.UniversalApiContract.winmd  C:\Program Files (x86)\Windows Kits\10\References\10.0.17763.0\Windows.Foundation.UniversalApiContract\7.0.0.0\Windows.Foundation.UniversalApiContract.winmd (Copy Local = False)

Windows.Foundation.FoundationContract.winmd  C:\Program Files (x86)\Windows Kits\10\References\10.0.17763.0\Windows.Foundation.FoundationContract\3.0.0.0\Windows.Foundation.FoundationContract.winmd (Copy Local = False)

*** This one is not part of the guidelines, this was aded by me 
C:\Users\{User}\.nuget\packages\microsoft.advertising.xaml\10.1805.7001\SDK\Windows Kits\10\ExtensionSDKs\Microsoft.Advertising.Xaml\10.0\References\CommonConfiguration\neutral\ Microsoft.Advertising.winmd (Copy Local = False)

Windows 10 Build Number:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [X] October 2018 Update (17763)
- [ ] Insider Build (build number: )

App min and target version:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [X] October 2018 Update (17763)
- [ ] Insider Build (xxxxx)

Device form factor:
- [X] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

Visual Studio 
- [X] 2017 (version: 15.9.2 )
- [ ] 2017 Preview (version: )

**Comment by freistli** [comment]
I hit the same issue with a WinForm project too.

Then tried to use WinRTC to wrapper a custom XAML control, which hosts AdControl, and then add project reference to WinForm. And packaging Winform as MSIX. But failed on another error:  cannot load System.Runtime, version=4.2.1....

Seems I have to convert WInForm to .Net Core? I don't want to do that because no Designer.

XAML ISLAND+WINRTC Nuget is a challenge situation. Especially for this AdControl, because it has UI, it is hard to use windows.activatableClass.outOfProcessServer to workaround this.

Still researching....

Any insights will be great.

**Comment by marb2000** [comment]
Adding the Ad Banner should be similar to adding a [custom control or WinUI 2 scenario](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/host-custom-control-with-xaml-islands). Did you try it. Is this still important?

**Comment by feliceferri** [comment]
Hi! Thank you for the follow up.

Much appreciated it

Yeah, unfortunately the tooling by that time wasn't there yet, so I changed
the strategy, but I'll planify to try it again with the WinUI 2 tooling

Thanks!!

Felice,

**Comment by marb2000** [comment]
No worry I have just released that Ad control is no longer [supported](https://docs.microsoft.com/en-us/windows/uwp/monetize/adcontrol-in-xaml-and--net).  This is what the documentation says:

> **As of June 1, 2020, the Microsoft Ad Monetization platform for Windows UWP apps will be shut down. **

So closing the bug.

**Comment by feliceferri** [comment]
Oh!, thank you for being so kind, and letting me know.!

I really thank you!

Felice,

PD: I'm just heart broken, was reached by a Facebook recruiter about a
month ago, passed the Tech Interview, off the record, it seems I was the
pick of the Hiring Manager, it was supposed to be an L5 position, and today
I got the news the Law Firm couldn't move me forward with the O1A visa.
