### ISSUE TITLE
Add targets file for WindowsXamlHost nugets to automaticly reference the Windows references

### ISSUE THREAD

**Issue by nmetulev** [windows-toolkit/Microsoft.Toolkit.Win32#66]
## I'm submitting a...

  
- Feature request (UserVoice request: )

## Current behavior
When developers use the WindowsXamlHost nuget packages they need to add all the references manually to use Windows UWP APIs: https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-enhance#first-set-up-your-project

## Expected behavior
The nuget packages should add those references automatically via a targets file

## Environment

```
Nuget Package(s): 
Microsoft.Toolkit.Forms.UI.XamlHost
Microsoft.Toolkit.Wpf.UI.XamlHost

Package Version(s): 

Windows 10 Build Number:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [x] October 2018 Update (17763)
- [ ] Insider Build (build number: )

App min and target version:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [x] October 2018 Update (17763)
- [ ] Insider Build (xxxxx)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

Visual Studio 
- [x] 2017 (version: )
- [ ] 2017 Preview (version: )

```

**Comment by liquidboy** [comment]
so tried pulling this repo and building/running the tests. Encountered the missing windows references. I know the team is looking to make this more workflow friendly . 

https://twitter.com/josefajardo/status/1088943046589218816
