### ISSUE TITLE
MediaPlaybackElement not rendering in WPF when using TimelineController

### ISSUE THREAD

**Issue by jusedit** [windows-toolkit/Microsoft.Toolkit.Win32#68]
## I'm submitting a...

Bug report (I searched for similar issues and did not find one)
 

## Current behavior

Accordingly to the ms docs "MediaPlayerElement control for Windows Forms and WPF" I have created a WPF with Microsoft.Toolkit referenced to be able to use UWP controls. The Video plays as expected but as soon as i enable mp.TimelineController and disable mp.Play the video is not rendered anymore. Audio still plays and mp.TimelineController.Position gives me reasonable values.

## Expected behavior

RealTimePlayback with TimelineController attached should be rendering 

## Minimal reproduction of the problem with instructions

```
	using System;
	using System.Windows;

	namespace WPF
	{
		public partial class MainWindow : Window
		{
			public MainWindow()
			{
				InitializeComponent();

				Microsoft.Toolkit.Wpf.UI.Controls.MediaPlayerElement mpe = new Microsoft.Toolkit.Wpf.UI.Controls.MediaPlayerElement();
				grid.Children.Add(mpe);

				Windows.Media.Playback.MediaPlayer wmp = new Windows.Media.Playback.MediaPlayer();
				mpe.SetMediaPlayer(wmp);

				wmp.Source = Windows.Media.Core.MediaSource.CreateFromUri(new Uri("C:/Users/DEXTER/Desktop/25.mp4"));
				wmp.RealTimePlayback = true;
				//wmp.Play(); // Working as expected.

				wmp.CommandManager.IsEnabled = false;
				wmp.TimelineController = new Windows.Media.MediaTimelineController();
				wmp.TimelineController.Start(); // Not rendering Video. Only Audio.
			}
		}
	}

```

## Environment

```
Nuget Package(s): 
Microsoft.Toolkit.Wpf.UI.Controls 5.0.0-preview.gb86cb1c4cb
Microsoft.Toolkit.Wpf.UI.XamlHost 5.0.0-preview.gb86cb1c4cb

Package Version(s): 
5.0.0-preview.gb86cb1c4cb
5.0.0-preview.gb86cb1c4cb

Windows 10 Build Number:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [x] Insider Build (build number: 18262.1000)

App min and target version:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [x] October 2018 Update (17763)
- [ ] Insider Build (xxxxx)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

Visual Studio 
- [x] 2017 (version: 15.8.7)
- [x] 2017 Preview (version: 15.9.0)

```

**Comment by azchohfi** [comment]
Hello @jusedit and @DB1307. Is this still an issue with the latest MyGet (https://dotnet.myget.org/feed/uwpcommunitytoolkit/package/nuget/Microsoft.Toolkit.Wpf.UI.Controls) and latest insider preview?

**Comment by QuantumDeveloper** [comment]
I am experiencing the same issues with styling and upscaling on nuget package version 6.0

**Comment by michael-hawker** [comment]
@marb2000 have you been testing MediaPlayer with the XI in WinUI 3?

**Comment by marb2000** [comment]
No yet. No sure even if we can test it until Mid-April. Adding @Austin-Lamb for awareness.

**Comment by marb2000** [comment]
@michael-hawker I'm closing this issue given it won't be fixed in XAML Islands. It should work in WinUI 3 in Desktop and Islands (when available)
