### ISSUE TITLE
Regressions when using winforms XAML host in 19H1 insider builds

### ISSUE THREAD

**Issue by lhak** [windows-toolkit/Microsoft.Toolkit.Win32#71]
## I'm submitting a...

Bug report (I searched for similar issues and did not find one)
 

## Current behavior

Compared to Windows 10 1809, the recent insider builds show a number of regressions when using the winforms XAML host and I am not sure if these are Windows bugs or if the host control code has to be adapted:

- ~~Every keystroke results in two characters in text boxes~~ Fixed
- ~~At least two host controls have to be created to render any UWP controls~~ Fixed
- ~~After DPI changes, only the backgrounds of the UWP controls are rendered and no interaction is possible~~ Fixed
- ~~FocusManager.GetFocusedElement() always returns null, even if a UWP control is focused~~ Breaking change. Use GetFocusedElement(XamlRoot)
- Changing focus to the next element in a UWP usercontrol with the tab key is not possible

## Expected behavior

No regressions

## Environment

```
Nuget Package(s): 

Package Version(s): 

Windows 10 Build Number:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [X] Insider Build (build number: 18272 )

App min and target version:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [ ] Insider Build (xxxxx)

Device form factor:
- [X] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

Visual Studio 
- [X] 2017 (version: 15.8)
- [ ] 2017 Preview (version: )

```

**Comment by azchohfi** [comment]
Hey @marb2000, are these issues being tracked? @ocalvo, is the "Update19H1" branch fixing those?

**Comment by marb2000** [comment]
About the FocusManager.GetFocusedElement() always returns null issue. This is by design. We introduced a new API FocusManager.GetFocusedElement(XamlRoot) that do the right thing. This is an expected Breaking Change from 1809 build to 19H1.

About the focus movementes between user controls, I think that these issues should be fixed by the @ocalvo focus fixes. @ocalvo make sure that this scenario works in your PR.

**Comment by lhak** [comment]
Thank you very much for the hint regarding the FocusManager API, with the change it works perfectly. The focus issue does only not seem to impact changes with the tab key, but setting focus to a UWP control with the mouse also does not seem to be possible. For example, if you click on a slider, it cannot be moved with the arrow keys later.

Can you also please take a look at issue #69, as I can still reproduce it?

**Comment by lhak** [comment]
Cannot reproduce these issues anymore on build 18632. Thank you!
