### ISSUE TITLE
UWP Canvas touch bug in XAML Islands

### ISSUE THREAD

**Issue by pcfulife** [windows-toolkit/Microsoft.Toolkit.Win32#77]
## I'm submitting a...

  
 

I found a XAML Island touch bug. I made two projects. One is UWP, another is WPF with XAML Islands. UWP is working well. But, WPF one is not working properly.

Sample project is just to show pointing status with blue squares. If I touch screen slightly it works well. But, if I touch it at random and rough, it sometimes cannot release some touch point, and squares are remained even I released all fingers from screen.

And, sometimes it crashes with COMException (See COMException.jpg file)

My project is based on .NET Core 3.0 and Windows Insider Preview (19H1). I think that it is not a bug of 19H1 because pure UWP project works well.

## Current behavior

See 3 jpg files. 

## Expected behavior

Same as pure UWP projects.

## Minimal reproduction of the problem with instructions

Here is a sample project and JPG files.
https://drive.google.com/open?id=1CuNYfd9mT06pxj95lAId3d4CZvJweZSu

A COMException Screenshot.
https://drive.google.com/file/d/1zz6OdsGqQ2Bd5nuISMva6BthkimRcZlw/view

Touch error logs
https://drive.google.com/open?id=1LSdnf5OqnKy3WzzdZLYoBKLyeAI6j6rn

Remained squares even all fingers are released from screen.
https://drive.google.com/open?id=1bx2vNWdK6doZrMrwNUwaio-FLf8TDWCN

I am sorry that some text is in Korean. I changed the Visual Studio Language settings to English. But, some Korean remained.

## Environment

```
Nuget Package(s): Microsoft.Toolkit.Wpf.UI.XamlHost

Package Version(s): v6.0.0-preview1

Windows 10 Build Number:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [x] Insider Build (build number: 18334.1)

App min and target version:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [x] October 2018 Update (17763)
- [ ] Insider Build (xxxxx)

Device form factor:
- [ ] Desktop
- [x] Mobile (HP Elitepad 1000 G2 (Atom Z3975, 4G RAM, Win10 RS5 17763)
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

Visual Studio 
- [ ] 2017 (version: )
- [x] 2019 Preview (version: 3.0)

```

**Comment by lindexi** [comment]
Suggestion: could you add the jpg file to issue rather than zip the jpg file to google drive? We can not see any image before we download the zip file.

**Comment by pcfulife** [comment]
@lindexi Sorry, I will upload JPG files in 5 minutes.

**Comment by marb2000** [comment]
I have updated the sample to the latest bits and I can't repro. Everything works as expected.
