### ISSUE TITLE
Panel.ZIndex does not work when there is a WindowsXamlHost control

### ISSUE THREAD

**Issue by chanallenk** [windows-toolkit/Microsoft.Toolkit.Win32#78]
## Issue
In WPF when using WindowsXAMLHost, since there is no way to put WPF controls inside of UWP, I tried to put the WPF control on top of the WindowsXAMLHost as a workaround, but unfortunately this does not work, even when using Panel.ZIndex. While I kind of understand why it doesn't work (due to the nature of how XAML Islands host its UWP controls), it would be a very useful feature as a workaround to not being able to put WPF controls inside of a UWP control.

## Environment

```
Nuget Package(s): 

Package Version(s): 

Windows 10 Build Number:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [ ] Insider Build (build number: )

App min and target version:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [ ] Insider Build (xxxxx)

Device form factor:
- [ ] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

Visual Studio 
- [ ] 2017 (version: )
- [ ] 2017 Preview (version: )

```

**Comment by chanallenk** [comment]
[WpfApp1XamlIsland.zip](https://github.com/windows-toolkit/Microsoft.Toolkit.Win32/files/2882456/WpfApp1XamlIsland.zip)
@Bmartin2013 Hello, apologies this is my first time with an account in this site. I have attached a sample app, you can see this behavior in MainWindow.xaml.

**Comment by michael-hawker** [comment]
@chanallenk this is a platform limitation. Can you file a request in the [WinUI](https://aka.ms/winui) repo?  Thanks.
