### ISSUE TITLE
Private field should start with _.

### ISSUE THREAD

**Issue by ocalvo** [windows-toolkit/Microsoft.Toolkit.Win32#86]
Private field should start with _.

_Originally posted by @azchohfi in https://github.com/windows-toolkit/Microsoft.Toolkit.Win32/pull/85/threads/MDIzOlB1bGxSZXF1ZXN0UmV2aWV3VGhyZWFkMTU4NDY4MDE4OnYy/unresolve_

Using a prefix like "_" is against the guide lines for non private members, however,  we should enforce the use of "this." before access to private fields to differentiate between parameters, private instance field and static field.

parameters: No prefix at all.
private fields: prefix with "this."
private static fields: prefix with class name "ClassName."

**Comment by michael-hawker** [comment]
We should be following the [CoreFX Guidelines](https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md) which call out to use `_` for private variables and not to use `this.` unless absolutely necessary.

There are also the [Framework Guidelines](https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/framework-design-guidelines-digest.md) which should overlap and we should also make use of.
