### ISSUE TITLE
Do you have control extensions for WPF?

### ISSUE THREAD

**Issue by hovek** [windows-toolkit/Microsoft.Toolkit.Win32#93]
I need this TextBox mask for WPF: https://docs.microsoft.com/en-us/windows/communitytoolkit/extensions/textboxmask
Is there a way to use it for WPF?

**Comment by michael-hawker** [comment]
Thanks @hovek, I've transferred this issue to our WPF/WinForms repository.  We haven't investigated providing control extensions for WPF like our UWP one here yet.  It sounds like an interesting project for someone though.

I'd imagine it'd have to be a port though, not sure how much shared logic there is, though we could leverage .NET Standard if there is.

**Comment by michael-hawker** [comment]
Similar note for WPF Behavior helpers that we have.

**Comment by marb2000** [comment]
At this point, there isn't in the roadmap to create more wrapper controls for XAML Islands. However you can use the WinUI 2 NumberBox control in to filter numbers. I do recommend to open this request in WinUI GitHub site if still needed.
Closing this issue.
