### ISSUE TITLE
When creating a new Window that has a second WindowsXamlHost using a new thread, application crashes after exiting that new window

### ISSUE THREAD

**Issue by chanallenk** [windows-toolkit/Microsoft.Toolkit.Win32#97]
## I'm submitting a...

Bug report (I searched for similar issues and did not find one) 
 

## Current behavior

In a Windows Application Packaging project. (WPF) when creating a second window through a new thread in order to use a second XAMLHost, after closing the second window and returning to the first window, the application will crash.

## Expected behavior

When creating a second window through a new thread, it should be able to exit properly without crashing.

## Minimal reproduction of the problem with instructions

[This is a sample project](https://github.com/chanallenk/WindowsXamlHostIssue)

Or:
1. Create a new Windows Application Packaging Project
2. In the MainWindow, create a XAML Island that uses a complex control (Like a Navigation View). 
3. Open a NewWindow using a separate thread. The NewWindow should have another XAML Island (of any control)
4. Close the NewWindow and return to your MainWindow
5. Move your mouse over the first XAML Island and attempt to interact with that control
6. Application will crash

## Environment

```
Nuget Package(s): 
Microsoft.Toolkit.Win32.UI.Controls.5.0.0
Microsoft.Toolkit.Wpf.UI.XamlHost.5.1.0

Windows 10 Build Number:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [X] October 2018 Update (17763)
- [ ] Insider Build (build number: )

App min and target version:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [X] October 2018 Update (17763)
- [ ] Insider Build (xxxxx)

Device form factor:
- [X] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

Visual Studio 
- [X] 2017 (version: )
- [ ] 2017 Preview (version: )

```

**Comment by michael-hawker** [comment]
Thanks @chanallenk for the report, it'd be good to know if this happens on the latest Insider build and with the 6.0 preview package.  Xaml Islands was still in preview for 17763, so some of these issues may be resolved.

**Comment by michael-hawker** [comment]
This may also be duplicate of #74?

**Comment by chanallenk** [comment]
@michael-hawker Yes, I have finally downloaded 18361 and this is no longer an issue. Thank you.
